//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SafariServices/_SFJavaScriptDialogViewDelegate-Protocol.h>

@class NSString, WBSJavaScriptDialogCompletionHandler, _SFJavaScriptDialogView;
@protocol _SFJavaScriptDialogControllerDelegate, _SFJavaScriptDialogPresenting;

@interface _SFJavaScriptDialogController : NSObject <_SFJavaScriptDialogViewDelegate>
{
    WBSJavaScriptDialogCompletionHandler *_completionHandler;
    _SFJavaScriptDialogView *_dialogView;
    int _webProcessIdentifier;
    id <_SFJavaScriptDialogControllerDelegate> _delegate;
    id <_SFJavaScriptDialogPresenting> _dialogPresenter;
}

+ (void)initialize;
@property(nonatomic) __weak id <_SFJavaScriptDialogPresenting> dialogPresenter; // @synthesize dialogPresenter=_dialogPresenter;
@property(nonatomic) __weak id <_SFJavaScriptDialogControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)javaScriptDialogView:(id)arg1 didSelectActionAtIndex:(long long)arg2 withPromptText:(id)arg3;
- (void)_tearDownPresentation;
- (void)_setUpPresentationWithMessage:(id)arg1 defaultText:(id)arg2 completionHandler:(id)arg3;
- (void)_setUpPresentationWithMessage:(id)arg1 completionHandler:(id)arg2;
- (_Bool)_isPresentingDialogView;
- (void)dismissDialogIfNeeded;
- (void)owningWebViewWillBecomeActive;
- (void)showPromptWithMessage:(id)arg1 defaultText:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)showConfirmWithMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)showAlertWithMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

