//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LSApplicationProxy, NSURL;

@interface _SFNavigationResult : NSObject
{
    long long _type;
    NSURL *_URL;
    LSApplicationProxy *_externalApplication;
}

+ (id)resultOfLoadingRequest:(id)arg1 isMainFrame:(_Bool)arg2 disallowRedirectToExternalApps:(_Bool)arg3;
+ (id)resultWithRedirectToExternalURL:(id)arg1;
+ (id)resultOfType:(long long)arg1 withURL:(id)arg2;
@property(readonly, nonatomic) LSApplicationProxy *externalApplication; // @synthesize externalApplication=_externalApplication;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)_initWithType:(long long)arg1 URL:(id)arg2 externalApplication:(id)arg3;

@end

