//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMutableDictionary;

@interface MFWeakObjectCache : NSObject
{
    CDUnknownBlockType _block;
    NSMutableDictionary *_dictionary;
    NSLock *_lock;
}

- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1 wasCached:(_Bool *)arg2;
- (id)objectForKey:(id)arg1;
- (void)dealloc;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

