//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <FrontBoardUIServices/NSCopying-Protocol.h>

@class FBSDisplay, FBSSceneClientSettings, FBSSceneSettings;

@interface FBUISceneParameters : NSObject <NSCopying>
{
    FBSDisplay *_display;
    FBSSceneSettings *_settings;
    FBSSceneClientSettings *_clientSettings;
}

+ (id)parametersForSpecification:(id)arg1;
@property(copy, nonatomic) FBSSceneClientSettings *clientSettings; // @synthesize clientSettings=_clientSettings;
@property(copy, nonatomic) FBSSceneSettings *settings; // @synthesize settings=_settings;
@property(retain, nonatomic) FBSDisplay *display; // @synthesize display=_display;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateClientSettingsWithBlock:(CDUnknownBlockType)arg1;
- (void)updateSettingsWithBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithSpecification:(id)arg1;

@end

