//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ITMLKit/JSExport-Protocol.h>

@class IKDOMDocument, IKJSMediaItem, IKJSPlaylist, NSString;

@protocol IKJSPlayer <JSExport>
@property(retain, nonatomic) IKDOMDocument *overlayDocument;
@property(nonatomic) double playbackRate;
@property(readonly, nonatomic) IKJSMediaItem *previousMediaItem;
@property(readonly, nonatomic) IKJSMediaItem *nextMediaItem;
@property(readonly, nonatomic) IKJSMediaItem *currentMediaItem;
@property(retain, nonatomic) IKJSPlaylist *playlist;
@property(readonly, nonatomic) NSString *playbackState;
- (void)stop;
- (void)pause;
- (void)play;
- (void)present;
- (void)seekToTime:(double)arg1;
- (id)init;
@end

