//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (MSPContainerAdditions)
- (id)_maps_arrayWithObjectsConformingToProtocols:(id)arg1;
- (unsigned long long)_maps_indexOfObjectCorrespondingToImmutableObject:(id)arg1;
- (id)_maps_indexesOfObjectsCorrespondingToImmutableObjects:(id)arg1;
@end

