//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/JSExport-Protocol.h>

@class JSValue, NSString;

@protocol SKUIJSUpdatableAssetController <JSExport>
- (void)refreshCachedManifest:(JSValue *)arg1;
- (NSString *)newestCachedManifestVersion;
- (NSString *)loadResource:(NSString *)arg1;
- (NSString *)currentManifestVersion;
@end

