//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface UIPDFHighlightLayer : CALayer
{
    struct CGPath *_clipPath;
    struct CGPath *_borderPath;
    struct CGPoint offset;
}

@property(nonatomic) struct CGPoint offset; // @synthesize offset;
@property(nonatomic) struct CGPath *borderPath; // @dynamic borderPath;
@property(nonatomic) struct CGPath *clipPath; // @dynamic clipPath;
- (void)dealloc;

@end

