//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@interface SBControlCenterDefaults : SBAbstractSpringBoardDefaultDomain
{
}

- (void)_bindAndRegisterDefaults;

// Remaining properties
@property(readonly, nonatomic, getter=isControlCenterDemo) _Bool controlCenterDemo; // @dynamic controlCenterDemo;
@property(readonly, nonatomic) _Bool shouldAlwaysBeEnabled; // @dynamic shouldAlwaysBeEnabled;
@property(readonly, nonatomic) _Bool shouldDisableLaunchingClockToTimer; // @dynamic shouldDisableLaunchingClockToTimer;
@property(readonly, nonatomic) _Bool shouldDisableScreenRecordingButton; // @dynamic shouldDisableScreenRecordingButton;

@end

