//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@class NSDictionary;

@interface SBWorkspaceDefaults : SBAbstractSpringBoardDefaultDomain
{
}

- (void)_bindAndRegisterDefaults;

// Remaining properties
@property(readonly, nonatomic) _Bool alwaysBreadcrumb; // @dynamic alwaysBreadcrumb;
@property(readonly, nonatomic, getter=isLegacyWorkspaceLoggingEnabled) _Bool legacyWorkspaceLoggingEnabled; // @dynamic legacyWorkspaceLoggingEnabled;
@property(readonly, nonatomic, getter=isMedusaEnabled) _Bool medusaEnabled; // @dynamic medusaEnabled;
@property(readonly, nonatomic) _Bool neverBreadcrumb; // @dynamic neverBreadcrumb;
@property(retain, nonatomic) NSDictionary *sideAppState; // @dynamic sideAppState;

@end

