//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PassKit/NSObject-Protocol.h>

@class NSString;
@protocol PKPassLibraryDataProvider, PKPassbookSettingsOptionsDelegate, PKPaymentDataProvider, PKPaymentSetupDelegate;

@protocol PKPassbookSettingsDataSource <NSObject>
- (_Bool)showPassState;
- (_Bool)deviceInRestrictedMode;
- (_Bool)deviceSupportsInAppPayments;
- (_Bool)secureElementIsProductionSigned;
- (NSString *)secureElementID;
- (id <PKPassbookSettingsOptionsDelegate>)optionsDelegate;
- (id <PKPaymentDataProvider>)paymentDataProvider;
- (id <PKPassLibraryDataProvider>)passLibraryDataProvider;
- (id <PKPaymentSetupDelegate>)setupDelegate;
@end

