//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class AVExternalDevice, MPAVController, MPMediaQuery, UIView;
@protocol MCDCarDisplayServiceProvider;

@interface MCD_OLD_TableViewController : UITableViewController
{
    id <MCDCarDisplayServiceProvider> _serviceProvider;
    MPAVController *_player;
    MPMediaQuery *_query;
    _Bool _viewHasAppeared;
    UIView *_nowPlayingButton;
    AVExternalDevice *_externalDevice;
    _Bool _alwaysShowNavBar;
    _Bool _limitedUI;
    _Bool _topLevel;
}

+ (void)_adjustTintColorForSubviewsInCell:(id)arg1 didHighlight:(_Bool)arg2;
+ (id)addAlbumArtViewWithImage:(id)arg1 toCell:(id)arg2 rowHeight:(double)arg3;
+ (id)addAlbumArtViewFromItem:(id)arg1 toCell:(id)arg2 rowHeight:(double)arg3;
+ (void)addTemplateImage:(id)arg1 toCell:(id)arg2;
+ (void)removeImageFromCell:(id)arg1;
@property(nonatomic) _Bool topLevel; // @synthesize topLevel=_topLevel;
@property(nonatomic) _Bool limitedUI; // @synthesize limitedUI=_limitedUI;
@property(nonatomic) _Bool alwaysShowNavBar; // @synthesize alwaysShowNavBar=_alwaysShowNavBar;
@property(readonly, nonatomic) MPMediaQuery *query; // @synthesize query=_query;
@property(readonly, nonatomic) MPAVController *player; // @synthesize player=_player;
@property(readonly, nonatomic) id <MCDCarDisplayServiceProvider> serviceProvider; // @synthesize serviceProvider=_serviceProvider;
@property(nonatomic) _Bool viewHasAppeared; // @synthesize viewHasAppeared=_viewHasAppeared;
- (void).cxx_destruct;
- (id)viewControllerForRowAtIndexPath:(id)arg1;
- (void)_updateNowPlayingVisibility;
- (void)_presentNowPlayingViewController;
- (void)_nowPlayingButtonTapped:(id)arg1;
- (void)_itemChanged:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 shouldChangeFocusedItem:(id)arg2 fromRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)hasRowsToDisplay;
- (id)dequeueReusableCarDisplayCellForTableView:(id)arg1 indexPath:(id)arg2;
- (id)preferredFocusedItem;
- (void)_limitedUIDidChange;
- (id)initWithQuery:(id)arg1 player:(id)arg2 serviceProvider:(id)arg3;

@end

