//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MusicCarDisplayUI/NSObject-Protocol.h>

@class MCDNowPlayingViewController;

@protocol MCDNowPlayingViewControllerDelegate <NSObject>

@optional
- (void)nowPlayingViewControllerLike:(MCDNowPlayingViewController *)arg1;
- (void)nowPlayingViewControllerToggleRepeat:(MCDNowPlayingViewController *)arg1;
- (void)nowPlayingViewControllerToggleShuffle:(MCDNowPlayingViewController *)arg1;
- (_Bool)nowPlayingViewControllerCanLike:(MCDNowPlayingViewController *)arg1;
- (_Bool)nowPlayingViewControllerCanRepeat:(MCDNowPlayingViewController *)arg1;
- (_Bool)nowPlayingViewControllerCanShuffle:(MCDNowPlayingViewController *)arg1;
- (void)nowPlayingViewController:(MCDNowPlayingViewController *)arg1 didSendAction:(long long)arg2 state:(long long)arg3;
- (_Bool)nowPlayingViewController:(MCDNowPlayingViewController *)arg1 shouldEnableButton:(long long)arg2;
- (_Bool)nowPlayingViewController:(MCDNowPlayingViewController *)arg1 buttonShouldBeActive:(long long)arg2;
- (_Bool)nowPlayingViewController:(MCDNowPlayingViewController *)arg1 shouldDisplayButton:(long long)arg2 withImage:(out id *)arg3 tinted:(out _Bool *)arg4;
@end

