//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImage;

@interface MCDTransportControlView : UIView
{
    _Bool _progressActive;
    int _mode;
    UIButton *_leftButton;
    UIButton *_playPauseButton;
    UIButton *_fastForwardButton;
    UIImage *_pauseImage;
}

@property(retain, nonatomic) UIImage *pauseImage; // @synthesize pauseImage=_pauseImage;
@property(nonatomic) _Bool progressActive; // @synthesize progressActive=_progressActive;
@property(readonly, nonatomic) UIButton *fastForwardButton; // @synthesize fastForwardButton=_fastForwardButton;
@property(readonly, nonatomic) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(readonly, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIImage *defaultFastForwardButtonImage;
@property(readonly, nonatomic) UIImage *defaultLeftButtonImage;
- (void)_updateProgressActive;
- (struct CGSize)intrinsicContentSize;
- (void)_addConstraints;
- (void)_createSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

