//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthKit/HKSampleType.h>

@interface HKCategoryType : HKSampleType
{
}

+ (void)_insertCode:(long long)arg1 forIdentifier:(id)arg2;
- (_Bool)_validateMetadata:(id)arg1 error:(id *)arg2;
- (long long)_defaultValue;
- (_Bool)_acceptsValue:(long long)arg1;

@end

