//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HDAchievementDeduplicator : NSObject
{
}

+ (_Bool)_isDayEqualityRequiredForAchievementType:(unsigned long long)arg1;
+ (_Bool)_isWeekEqualityRequiredForAchievementType:(unsigned long long)arg1;
+ (_Bool)_shouldCheckValueEqualityForAchievementType:(unsigned long long)arg1;
+ (unsigned long long)_deduplicationStrategyForAchievementType:(unsigned long long)arg1;
+ (unsigned long long)_pickWinningAchievementWithAdded:(id)arg1 existing:(id)arg2;
+ (void)findDuplicatesInAddedAchievements:(id)arg1 existingAchievements:(id)arg2 foundDuplicatesInAdded:(id *)arg3 duplicatesInExisting:(id *)arg4;

@end

