//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/HDAchievementEngineDelegate-Protocol.h>

@class HKActivitySummary, NSArray, NSCalendar, NSString;
@protocol HDHealthDaemon, OS_dispatch_queue;

@interface HDAchievementDoctor : NSObject <HDAchievementEngineDelegate>
{
    id <HDHealthDaemon> _healthDaemon;
    NSObject<OS_dispatch_queue> *_queue;
    NSCalendar *_calendar;
    HKActivitySummary *_currentActivitySummary;
    HKActivitySummary *_yesterdayActivitySummary;
    NSArray *_workouts;
    NSArray *_workoutEndDates;
}

+ (id)_achievementsInSet:(id)arg1 missingFromSet:(id)arg2;
- (void).cxx_destruct;
- (id)sessionsEndingAfterAnchor:(long long)arg1 newAnchor:(long long *)arg2;
- (unsigned long long)numberOfSessionsCompletedAfterDate:(id)arg1 beforeDate:(id)arg2 minimumSessionDuration:(double)arg3;
- (unsigned long long)stepsTakenToday;
- (unsigned long long)stepsTakenYesterday;
- (unsigned long long)standingHoursToday;
- (unsigned long long)standingHoursYesterday;
- (double)briskMinutesToday;
- (double)briskMinutesYesterday;
- (double)caloriesBurnedToday;
- (double)caloriesBurnedYesterday;
- (id)energyBurnedGoalToday;
- (id)energyBurnedGoalYesterday;
- (long long)activitySummaryIndexToday;
- (id)currentDate;
- (id)_achievementsGroupedByActivityCacheIndex:(id)arg1;
- (id)_fetchAchievementsWithError:(id *)arg1;
- (id)_fetchWorkoutsSortedByEndDateWithError:(id *)arg1;
- (id)_fetchActivitySummariesOrderedByCacheIndexWithError:(id *)arg1;
- (id)_newEmptyActivitySummaryWithStartDate:(id)arg1 startDateComponents:(id)arg2 calorieGoal:(id)arg3;
- (_Bool)_isActivitySummary:(id)arg1 oneDayAfterActivitySummary:(id)arg2;
- (id)_queue_findExpectedAchievements:(id)arg1 missingFromAchievements:(id)arg2;
- (id)_queue_detectAchievementsForActivitySummaries:(id)arg1 workouts:(id)arg2 getResultingKeyValues:(id *)arg3;
- (_Bool)_queue_detectMissingAchievements:(id *)arg1 resultingKeyValues:(id *)arg2 error:(id *)arg3;
- (_Bool)_queue_saveMissingAchievements:(id)arg1 keyValues:(id)arg2 error:(id *)arg3;
- (void)runAchievementsFixupAsDryRun:(_Bool)arg1 persistingResultingKeyValues:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithHealthDaemon:(id)arg1 targetQueue:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

