//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/HDSyncEntity-Protocol.h>

@class HDNanoSyncRestoreSession, HDNanoSyncSession, HDSQLitePredicate, NSArray;
@protocol HDHealthDaemon;

@protocol HDNanoSyncEntity <HDSyncEntity>
+ (unsigned long long)supportedNanoSyncDirectionsForProtocolVersion:(int)arg1;
+ (int)nanoSyncObjectType;

@optional
+ (_Bool)supportsSpeculativeNanoSyncChanges;
+ (Class)receivingSyncEntityClassForNanoSyncProtocolVersion:(int)arg1;
+ (int)outgoingNanoSyncObjectTypeForNanoSyncProtocolVersion:(int)arg1;
+ (unsigned long long)syncObjectLimitForNanoSyncMessage;
+ (HDSQLitePredicate *)nanoSyncPredicateForSession:(HDNanoSyncSession *)arg1;
+ (long long)finalAnchorForNanoSyncRestoreSession:(HDNanoSyncRestoreSession *)arg1 healthDaemon:(id <HDHealthDaemon>)arg2 error:(id *)arg3;
+ (NSArray *)objectsForNanoSyncRestoreSession:(HDNanoSyncRestoreSession *)arg1 syncAnchorRange:(struct HDSyncAnchorRange)arg2 lastSyncAnchor:(long long *)arg3 healthDaemon:(id <HDHealthDaemon>)arg4 error:(id *)arg5;
@end

