//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/HDDataSyncEntity.h>

@interface HDSampleSyncEntity : HDDataSyncEntity
{
}

+ (_Bool)supportsSpeculativeNanoSyncChanges;
+ (id)_companionNanoSyncPredicateConjunctionForSession:(id)arg1;
+ (id)_appleWatchSamplesPredicateForSession:(id)arg1;
+ (id)_defaultCompanionNanoSyncSampleAgePredicateForSession:(id)arg1;
+ (id)nanoSyncPredicateForSession:(id)arg1;
+ (id)_nanoSyncWatchRestorePredicatesWithSession:(id)arg1;
+ (id)_predicateForNanoSyncRestoreSession:(id)arg1 healthDaemon:(id)arg2 error:(id *)arg3;
+ (long long)finalAnchorForNanoSyncRestoreSession:(id)arg1 healthDaemon:(id)arg2 error:(id *)arg3;
+ (id)objectsForNanoSyncRestoreSession:(id)arg1 syncAnchorRange:(struct HDSyncAnchorRange)arg2 lastSyncAnchor:(long long *)arg3 healthDaemon:(id)arg4 error:(id *)arg5;
+ (unsigned long long)supportedNanoSyncDirectionsForProtocolVersion:(int)arg1;
+ (int)nanoSyncObjectType;

@end

