//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/HDServerInterface-Protocol.h>

@class NSDate, NSError, NSUUID, _HKFirstPartyWorkoutSnapshot;

@protocol HDServer <HDServerInterface>
- (void)deliverWorkoutSessionError:(NSError *)arg1 forSessionUUID:(NSUUID *)arg2;
- (void)deliverWorkoutSessionChangedToState:(long long)arg1 fromState:(long long)arg2 date:(NSDate *)arg3 forSessionUUID:(NSUUID *)arg4;
- (void)nukeActiveWorkoutServers;
- (void)pauseActiveWorkoutsWithCompletion:(void (^)(void))arg1;
- (_HKFirstPartyWorkoutSnapshot *)firstPartyWorkoutSnapshot;
- (_Bool)hasActiveWorkouts;
- (void)invalidate;
- (void)start;
@end

