//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/NSObject-Protocol.h>

@class HDSQLiteDatabase, HDSQLiteStatement, NSArray, NSDate, NSSet, NSString, NSUUID;

@protocol HDSQLiteEntity <NSObject>
+ (NSString *)associationPropertyForEntityClass:(Class)arg1;
+ (NSString *)disambiguatedSQLForProperty:(NSString *)arg1;
+ (NSSet *)foreignDatabaseTablesToDelete;
+ (NSString *)foreignKeyColumnForTable:(NSString *)arg1;
+ (NSString *)foreignDatabaseTableForProperty:(NSString *)arg1;
+ (NSString *)foreignDatabaseColumnForProperty:(NSString *)arg1;
+ (NSSet *)joinClausesForProperty:(NSString *)arg1;
+ (NSArray *)allDatabaseColumnNames;
+ (NSString *)disambiguatedDatabaseTable;
+ (Class)entityForProperty:(NSString *)arg1;
+ (NSArray *)columnsDefinition;
+ (NSArray *)tableAliases;
+ (NSString *)databaseTable;
+ (NSString *)databaseName;
+ (HDSQLiteStatement *)deleteStatementWithProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (_Bool)getValuesForProperties:(NSArray *)arg1 withDatabase:(HDSQLiteDatabase *)arg2 applier:(void (^)(NSArray *, struct HDSQLiteRow *))arg3;
- (_Bool)deleteFromDatabase:(HDSQLiteDatabase *)arg1 error:(id *)arg2;
- (_Bool)getValuesForProperties:(NSArray *)arg1 database:(HDSQLiteDatabase *)arg2 handler:(void (^)(NSArray *, struct HDSQLiteRow *))arg3;
- (NSUUID *)UUIDForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (NSDate *)dateForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (_Bool)booleanForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;
- (id)valueForProperty:(NSString *)arg1 database:(HDSQLiteDatabase *)arg2;

@optional
+ (NSString *)columnNameForSortIdentifier:(NSString *)arg1;
@end

