//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableString.h>

@interface NSMutableString (ICSWriter)
- (void)_ICSStringParameterName:(id)arg1 value:(id)arg2;
- (void)_ICSStringAppendingParameterName:(id)arg1;
- (void)_ICSEscapeParameterQuotedValue;
- (void)_ICSEscapeParameterValue;
- (void)_ICSEscapePropertyValue;
- (void)_ICSStripControlChracters;
- (void)_ICSRemoveCharactersFromSet:(id)arg1;
@end

