//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppConduit/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol ACXInstallOperationProtocol <NSObject>
- (void)cancel;
- (void)beginInstallOperationForIdentifier:(NSString *)arg1 settings:(NSDictionary *)arg2 installPlaceholder:(_Bool)arg3 completion:(void (^)(NSError *))arg4;
@end

