//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (ABTelephonyUtilities)
+ (id)cnui_faceTimeURLWithDestinationID:(id)arg1 contact:(id)arg2 audioOnly:(_Bool)arg3;
+ (id)ab_URLWithTelephoneNumber:(id)arg1 contact:(id)arg2;
+ (id)ab_faceTimeURLWithDestinationID:(id)arg1;
@end

