//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NotesShared/ICAttachmentModel.h>

@class MKMapSnapshotter;

@interface ICAttachmentMapModel : ICAttachmentModel
{
    MKMapSnapshotter *_mapSnapshotter;
}

+ (id)contentInfoTextWithAttachmentCount:(unsigned long long)arg1;
@property(retain) MKMapSnapshotter *mapSnapshotter; // @synthesize mapSnapshotter=_mapSnapshotter;
- (void).cxx_destruct;
- (void)generatePreviews;
- (_Bool)generateAsynchronousPreviews;
- (_Bool)needToGeneratePreviews;
- (CDUnknownBlockType)genericBrickThumbnailCreator;
- (CDUnknownBlockType)genericListThumbnailCreator;
- (_Bool)hasPreviews;

@end

