//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class ICGroup, ICPerson, NSNumber, NSString, UIImage;

@interface ICAuthor : NSManagedObject
{
}

+ (id)currentAuthorInGroup:(id)arg1 context:(id)arg2;
+ (id)authorForPerson:(id)arg1 inGroup:(id)arg2 createIfNecessary:(_Bool)arg3 context:(id)arg4;
@property(nonatomic) unsigned long long authorStatus;
@property(readonly, nonatomic) UIImage *icon;
@property(readonly, nonatomic) NSString *name;

// Remaining properties
@property(retain, nonatomic) ICGroup *group; // @dynamic group;
@property(retain, nonatomic) ICPerson *person; // @dynamic person;
@property(retain, nonatomic) NSNumber *status; // @dynamic status;

@end

