//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudKit/CKFetchRecordsOperation.h>

@class NSArray, NSDictionary;

@interface ICCloudObjectFetchOperation : CKFetchRecordsOperation
{
    NSArray *_cloudObjects;
    CDUnknownBlockType _perCloudObjectCompletionBlock;
    CDUnknownBlockType _fetchCloudObjectsCompletionBlock;
    NSDictionary *_cloudObjectsByRecordID;
}

@property(retain) NSDictionary *cloudObjectsByRecordID; // @synthesize cloudObjectsByRecordID=_cloudObjectsByRecordID;
@property(copy) CDUnknownBlockType fetchCloudObjectsCompletionBlock; // @synthesize fetchCloudObjectsCompletionBlock=_fetchCloudObjectsCompletionBlock;
@property(copy) CDUnknownBlockType perCloudObjectCompletionBlock; // @synthesize perCloudObjectCompletionBlock=_perCloudObjectCompletionBlock;
@property(retain) NSArray *cloudObjects; // @synthesize cloudObjects=_cloudObjects;
- (void).cxx_destruct;
- (void)perRecordCompletionWithRecord:(id)arg1 recordID:(id)arg2 error:(id)arg3;
- (void)perRecordProgressWithRecordID:(id)arg1 progress:(double)arg2;
- (void)setupProgressAndCompletionBlocks;
- (id)initWithRecordIDs:(id)arg1;
- (id)initWithCloudObjects:(id)arg1;

@end

