//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Notes/ICGenerateSearchIndexStringsOperation.h>

@interface ICGenerateLocationSearchIndexStringsOperation : ICGenerateSearchIndexStringsOperation
{
    double _latitude;
    double _longitude;
}

@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
- (void)main;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2;

@end

