//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface AAQuotaDepletionAlert : NSObject
{
    NSString *_dataclass;
}

+ (_Bool)_isDisabledDataclass:(id)arg1;
- (void).cxx_destruct;
- (id)_deviceSpecificLocalizedString:(id)arg1;
- (_Bool)showIfNecessaryWithHandler:(CDUnknownBlockType)arg1;
- (void)showWithHandler:(CDUnknownBlockType)arg1;
- (id)initForDataclass:(id)arg1;
- (id)init;

@end

