//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FitnessUI/NSSecureCoding-Protocol.h>

@class NSDate;

@interface FUHourlySedentaryActivityInfo : NSObject <NSSecureCoding>
{
    NSDate *_startDate;
    long long _sedentaryState;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) long long sedentaryState; // @synthesize sedentaryState=_sedentaryState;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

