//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class GKLabel, NSString;

@interface GKMoreExistSectionFooterView : UICollectionReusableView
{
    GKLabel *_label;
}

+ (double)defaultHeight;
+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) GKLabel *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *text;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

