//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, UIColor, UIImage;

@interface HKDataCategory : NSObject
{
    NSMutableArray *_dataUnits;
    NSMutableDictionary *_cachedGradients;
    NSMutableDictionary *_cachedRoundedCornerGradients;
    UIColor *_topColor;
    UIColor *_bottomColor;
    long long _categoryID;
    NSString *_displayName;
    NSString *_listIconName;
    UIImage *_listIcon;
    UIImage *_dashboardIcon;
    UIImage *_shareIcon;
}

@property(readonly, nonatomic) UIImage *shareIcon; // @synthesize shareIcon=_shareIcon;
@property(readonly, nonatomic) UIImage *dashboardIcon; // @synthesize dashboardIcon=_dashboardIcon;
@property(readonly, nonatomic) UIImage *listIcon; // @synthesize listIcon=_listIcon;
@property(readonly, nonatomic) NSString *listIconName; // @synthesize listIconName=_listIconName;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, nonatomic) long long categoryID; // @synthesize categoryID=_categoryID;
- (void).cxx_destruct;
- (id)_generateGradientOfHeight:(double)arg1;
- (id)_generateRoundedCornerGradientWithHeight:(double)arg1;
- (id)roundedCornerGradientWithHeight:(double)arg1;
- (id)gradientWithHeight:(double)arg1;
- (void)addDataUnit:(id)arg1;
@property(readonly, nonatomic) NSArray *dataUnits;
@property(readonly, nonatomic) _Bool isMeCategory;
@property(readonly, nonatomic) UIColor *seriesColor;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

