//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMassFormatter;

@interface HKPersonWeightFormatter : NSObject
{
    NSMassFormatter *_massFormatter;
    long long _localWeightUnit;
}

+ (id)sharedFormatter;
@property(readonly, nonatomic) long long localWeightUnit; // @synthesize localWeightUnit=_localWeightUnit;
- (void).cxx_destruct;
- (id)stringFromWeightValue:(double)arg1 inUnit:(long long)arg2;
- (id)stringFromWeightInKilograms:(id)arg1;
- (void)_updateRoundingIncrement;
- (void)_localeChanged:(id)arg1;
- (void)dealloc;
- (void)_commonInit;
- (id)init;

@end

