//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Weather/WeatherJSONHTTPRequest.h>

@class NSMutableArray;
@protocol WeatherUpdaterDelegate;

@interface TWCUpdater : WeatherJSONHTTPRequest
{
    NSMutableArray *_updatingCities;
    NSMutableArray *_pendingCities;
    CDUnknownBlockType _weatherCompletionUpdaterHandler;
    id <WeatherUpdaterDelegate> _delegate;
}

@property(nonatomic) __weak id <WeatherUpdaterDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType weatherCompletionUpdaterHandler; // @synthesize weatherCompletionUpdaterHandler=_weatherCompletionUpdaterHandler;
- (void).cxx_destruct;
- (_Bool)isUpdatingCity:(id)arg1;
- (id)aggregateDictionaryDomain;
- (void)failWithError:(id)arg1;
- (void)didProcessJSONObject;
- (void)loadRequestForURLPortion:(id)arg1;
- (void)handleCompletionForCity:(id)arg1 withUpdateDetail:(unsigned long long)arg2;
- (void)handleNilCity;
- (void)processJSONObject:(id)arg1;
- (void)_processLinks:(id)arg1;
- (void)_processDailyForecasts:(id)arg1;
- (void)_processHourlyForecasts:(id)arg1;
- (void)_processCurrentConditions:(id)arg1;
- (id)_GMTOffsetRegularExpression;
- (id)_ISO8601DateFormatter;
- (id)_ISO8601Calendar;
- (void)_failed:(unsigned long long)arg1;
- (void)addCityToPendingQueue:(id)arg1;
- (void)_updateNextPendingCity;
- (void)runAndClearWeatherCompletionWithDetail:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;
- (void)failCity:(id)arg1;
- (void)parsedResultCity:(id)arg1;
- (_Bool)isDataValid:(id)arg1;

@end

