//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BBSettingsGateway, NPSManager;

@interface BLTDNDSyncInternal : NSObject
{
    unsigned long long _bulletinBoardDNDState;
    _Bool _isDNDMirrorEnabled;
    BBSettingsGateway *_settingsGateway;
    NPSManager *_npsManager;
}

@property(readonly, nonatomic) unsigned long long bulletinBoardDNDState; // @synthesize bulletinBoardDNDState=_bulletinBoardDNDState;
@property(retain, nonatomic) NPSManager *npsManager; // @synthesize npsManager=_npsManager;
@property(nonatomic) _Bool isDNDMirrorEnabled; // @synthesize isDNDMirrorEnabled=_isDNDMirrorEnabled;
@property(retain, nonatomic) BBSettingsGateway *settingsGateway; // @synthesize settingsGateway=_settingsGateway;
- (void).cxx_destruct;
- (_Bool)_isChangeToDNDSettingObsoleteAtDate:(id)arg1 overrides:(id)arg2;
- (void)_updateSettingsGatewayTo:(_Bool)arg1 changeDate:(id)arg2;
- (void)synchronizeDNDEnabled:(_Bool)arg1 andChangeDate:(id)arg2;
- (void)setDoNotDisturb:(_Bool)arg1 changeDate:(id)arg2 updateSettingsGateway:(_Bool)arg3;
- (void)setPrivilegedSenderTypes:(unsigned long long)arg1;
- (void)setBehaviorOverrides:(id)arg1;
- (void)setBehaviorOverrideStatus:(long long)arg1;
- (void)setBehaviorOverrideTypes:(unsigned long long)arg1 changedDate:(id)arg2;
- (void)removeDNDHandlers;
- (void)setDNDHandlers;
- (void)updateDNDStateChangedByPreferencesSync:(_Bool)arg1;
- (void)updateDNDMirrorState;
- (void)dealloc;
- (id)init;

@end

