//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface BLTSectionConfiguration : NSObject
{
    NSDictionary *_configurations;
}

+ (id)sharedSectionConfiguration;
- (void).cxx_destruct;
- (id)_loadConfigurations;
- (_Bool)shouldSectionIDSettingsAlwaysSync:(id)arg1;
- (_Bool)hasSectionIDOptedOutOfAttachmentCoordination:(id)arg1;
- (_Bool)hasSectionIDOptedOutOfCoordination:(id)arg1 subtype:(long long)arg2 considerSubtype:(_Bool)arg3;
- (_Bool)hasSectionIDOptedOutOfCoordination:(id)arg1;
- (id)init;

@end

