//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BBSectionInfo, NSDictionary, NSString;

@interface BLTSectionInfoListItem : NSObject
{
    BBSectionInfo *_sectionInfo;
    NSDictionary *_overrides;
    NSString *_universalSectionID;
    NSString *_displayName;
}

@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *universalSectionID; // @synthesize universalSectionID=_universalSectionID;
@property(retain, nonatomic) NSDictionary *overrides; // @synthesize overrides=_overrides;
@property(retain, nonatomic) BBSectionInfo *sectionInfo; // @synthesize sectionInfo=_sectionInfo;
- (void).cxx_destruct;

@end

