//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <FuseUI/MusicNowPlayingVideoViewControllerDelegate-Protocol.h>

@class ADBannerView, MPAVItem, MPArtworkCatalog, MusicArtworkView, MusicNowPlayingVideoViewController, NSString, UIImage;
@protocol MusicNowPlayingItemViewControllerDelegate;

@interface MusicNowPlayingItemViewController : UIViewController <MusicNowPlayingVideoViewControllerDelegate>
{
    ADBannerView *_adBannerView;
    MPArtworkCatalog *_artworkCatalog;
    struct CGSize _artworkFittingSize;
    UIImage *_artworkImage;
    MusicArtworkView *_imageView;
    unsigned long long _itemType;
    MusicNowPlayingVideoViewController *_videoViewController;
    _Bool _hasProperApplicationStateForWantingVideoLayer;
    _Bool _hasVisibilityForWantingVideoLayer;
    _Bool _isConnectedToTVOutScreen;
    _Bool _wantsVideoLayer;
    CDUnknownBlockType _deferTransitionBlock;
    MPAVItem *_item;
    id <MusicNowPlayingItemViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <MusicNowPlayingItemViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) MPAVItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)_updateWantsVideoLayer;
- (void)_updateContentViewWithReload:(_Bool)arg1;
- (void)_updatePreferredContentSize;
- (void)_updateArtworkCatalogWithReload:(_Bool)arg1;
- (void)_unregisterForVideoViewControllerNotifications:(id)arg1;
- (void)_setWantsVideoLayer:(_Bool)arg1;
- (void)_setArtworkImage:(id)arg1;
- (void)_removeVideoViewController;
- (void)_removeArtworkImageView;
- (void)_removeAdBannerView;
- (void)_registerForVideoViewControllerNotifications:(id)arg1;
- (id)_placeholderArtwork;
- (void)_tvOutCapabiltiesDidChangeNotification:(id)arg1;
- (void)_playerFirstVideoFrameDidDisplayNotification:(id)arg1;
- (void)_itemTypeAvailableNotification:(id)arg1;
- (void)_itemArtworkDidChangeNotification:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
@property(nonatomic) _Bool canShowOverlayControls;
@property(nonatomic) _Bool overlayVideoControlsHidden;
- (void)updateArtworkImageForSize:(struct CGSize)arg1;
- (long long)transitionFromItemViewController:(id)arg1;
- (void)deferItemTransitionIfNeeded:(CDUnknownBlockType)arg1;
- (id)viewControllerForStoryboardPresentationFromBannerView:(id)arg1;
- (void)overlayBackButtonTapped:(id)arg1;
- (_Bool)videoController:(id)arg1 shouldDisplayAlertForError:(id)arg2;
- (id)artworkImage;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (id)initWithItem:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

