//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FuseUI/UIViewControllerAnimatedTransitioning-Protocol.h>

@class MusicTabBarController, NSString, UIView;

@interface MusicNowPlayingTransitionController : NSObject <UIViewControllerAnimatedTransitioning>
{
    CDUnknownBlockType _transitionStartBlock;
    CDUnknownBlockType _transitionFinishBlock;
    CDUnknownBlockType _transitionStopBlock;
    CDUnknownBlockType _transitionEndBlock;
    CDUnknownBlockType _transitionRubberBandEffectBlock;
    _Bool _hasFinishedTransition;
    UIView *_dimmingView;
    _Bool _dismissal;
    MusicTabBarController *_tabBarController;
}

@property(retain, nonatomic) MusicTabBarController *tabBarController; // @synthesize tabBarController=_tabBarController;
@property(nonatomic, getter=isDismissal) _Bool dismissal; // @synthesize dismissal=_dismissal;
- (void).cxx_destruct;
- (void)updateRubberbandingWithDistance:(double)arg1;
- (void)stopAnimation;
- (void)prepareTransition:(id)arg1;
- (void)cleanupTransition:(id)arg1;
- (void)animateTransition:(id)arg1 withDuration:(double)arg2 initialVelocity:(double)arg3 interactively:(_Bool)arg4 toFinalPositions:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

