//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <FuseUI/MusicClientContextConsuming-Protocol.h>
#import <FuseUI/MusicUpNextAggregateDataSourceDelegate-Protocol.h>
#import <FuseUI/MusicUpNextNowPlayingLockupViewDelegate-Protocol.h>
#import <FuseUI/MusicUpNextTableViewDelegate-Protocol.h>
#import <FuseUI/UITableViewDataSource-Protocol.h>
#import <FuseUI/UIViewControllerTransitioningDelegate-Protocol.h>

@class MusicAVPlayer, MusicClientContext, MusicUpNextAggregateDataSource, MusicUpNextNowPlayingLockupView, MusicUpNextTableView, NSIndexPath, NSString, SKUIClientContext, UIView;

@interface MusicUpNextViewController : UIViewController <UITableViewDataSource, MusicUpNextTableViewDelegate, MusicUpNextAggregateDataSourceDelegate, MusicUpNextNowPlayingLockupViewDelegate, MusicClientContextConsuming, UIViewControllerTransitioningDelegate>
{
    MusicUpNextTableView *_tableView;
    NSIndexPath *_indexPathForNowPlayingFrame;
    MusicUpNextNowPlayingLockupView *_nowPlayingView;
    UIView *_hairlineView;
    struct UIEdgeInsets _appliedEdgeInsets;
    _Bool _ignoreUpdates;
    _Bool _isReordering;
    _Bool _loadingCells;
    _Bool _didMutateWhileLoading;
    _Bool _shouldDismissOnItemChange;
    _Bool _hidesNowPlaying;
    _Bool _shouldDismissImmediately;
    MusicClientContext *_clientContext;
    MusicUpNextAggregateDataSource *_dataSource;
    MusicAVPlayer *_player;
    UIView *_itemContentViewContainerView;
}

+ (id)upNextViewControllerWithPlayer:(id)arg1;
@property(nonatomic) _Bool shouldDismissImmediately; // @synthesize shouldDismissImmediately=_shouldDismissImmediately;
@property(nonatomic) _Bool hidesNowPlaying; // @synthesize hidesNowPlaying=_hidesNowPlaying;
@property(readonly, nonatomic) _Bool shouldDismissOnItemChange; // @synthesize shouldDismissOnItemChange=_shouldDismissOnItemChange;
@property(readonly, nonatomic) UIView *itemContentViewContainerView; // @synthesize itemContentViewContainerView=_itemContentViewContainerView;
@property(retain, nonatomic) MusicAVPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) MusicUpNextAggregateDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) SKUIClientContext *clientContext;
- (void).cxx_destruct;
- (id)_translateTableViewUpdatesToMoveIfPossible:(id)arg1;
- (void)_updateTableViewInsets;
- (double)_maximumRowHeight;
- (void)_reloadNowPlayingView;
- (struct CGRect)_rectForQueue;
- (struct CGRect)_rectForNowPlayingAndQueue;
- (void)_playlistManagerDisableUserQueueModifcationsDidChange:(id)arg1;
- (void)_preferredContentSizeDidChange:(id)arg1;
- (void)prepareForDismissal;
- (void)_dismissUpNext;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)tableView:(id)arg1 didCancelReorderingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndReorderingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginReorderingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectContextualActionsButton:(id)arg2 forCell:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 pinView:(id)arg2 didUpdatePinLocation:(long long)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)nowPlayingLockupView:(id)arg1 touchEnded:(id)arg2;
- (void)aggregateDataSource:(id)arg1 didUpdate:(id)arg2;
- (id)contentScrollView;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(_Bool)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

