//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FuseUI/MusicContextualAlertAction.h>

@class MPAVController, MPPlaybackContext;

@interface MusicContextualUpNextAlertAction : MusicContextualAlertAction
{
    long long _insertionType;
    MPPlaybackContext *_playbackContext;
    MPAVController *_player;
}

+ (id)contextualUpNextActionWithEntityValueContext:(id)arg1 insertionType:(long long)arg2 alertController:(id)arg3 presentingViewController:(id)arg4 didDismissHandler:(CDUnknownBlockType)arg5;
- (void).cxx_destruct;
- (void)_handleUpNextAction;

@end

