//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FuseUI/MusicEntityHorizontalLockupViewDelegate-Protocol.h>

@class MusicContextualActionsHeaderLockupView;

@protocol MusicContextualActionsHeaderLockupViewDelegate <MusicEntityHorizontalLockupViewDelegate>

@optional
- (void)contextualActionsHeaderLockupViewWasSelected:(MusicContextualActionsHeaderLockupView *)arg1;
- (void)contextualActionsHeaderLockupViewDidSelectShareButton:(MusicContextualActionsHeaderLockupView *)arg1;
- (void)contextualActionsHeaderLockupViewDidSelectRadioButton:(MusicContextualActionsHeaderLockupView *)arg1;
- (void)contextualActionsHeaderLockupViewDidSelectLikeButton:(MusicContextualActionsHeaderLockupView *)arg1;
- (void)contextualActionsHeaderLockupViewDidSelectDownloadButton:(MusicContextualActionsHeaderLockupView *)arg1;
@end

