//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FuseUI/MusicEntityProviderDownloadInformationController.h>

#import <FuseUI/MPStoreDownloadManagerObserver-Protocol.h>

@class MusicStoreEntityProvider, NSArray, NSString;

@interface MusicStoreEntityProviderDownloadInformationController : MusicEntityProviderDownloadInformationController <MPStoreDownloadManagerObserver>
{
    unsigned long long _keepLocalEntityCount;
    unsigned long long _nonPurgeableEntityCount;
    NSArray *_relevantActiveDownloads;
    _Bool _shouldUseDetailedDownloadProgress;
    MusicStoreEntityProvider *_storeEntityProvider;
}

@property(readonly, nonatomic) MusicStoreEntityProvider *storeEntityProvider; // @synthesize storeEntityProvider=_storeEntityProvider;
- (void).cxx_destruct;
- (void)_enumateItemsForQuery:(id)arg1 withStoreIDsFromStoreItemMetadataContexts:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (unsigned long long)_countOfItemsForQuery:(id)arg1 withStoreIDsFromStoreItemMetadataContexts:(id)arg2;
- (void)_reloadStoreDownloadInformation;
- (void)_storeEntityProviderDidInvalidateNotification:(id)arg1;
- (void)downloadManager:(id)arg1 downloadDidProgress:(id)arg2;
- (void)downloadManager:(id)arg1 didAddActiveDownloads:(id)arg2 removeActiveDownloads:(id)arg3;
- (void)_endGeneratingDownloadInformationChanges;
- (void)_beginGeneratingDownloadInformationChanges;
- (void)dealloc;
- (id)initWithStoreEntityProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

