//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, NSMutableArray;

@interface MusicNowPlayingTitlesView : UIControl
{
    NSMutableArray *_labels;
    NSMutableArray *_marqueeViews;
    _Bool _needsViewUpdate;
    _Bool _marqueeEnabled;
    _Bool _clampLabels;
    NSArray *_attributedTexts;
    struct UIEdgeInsets _contentInset;
    struct UIEdgeInsets _marqueeFadeEdgeInsets;
}

@property(nonatomic) _Bool clampLabels; // @synthesize clampLabels=_clampLabels;
@property(nonatomic) struct UIEdgeInsets marqueeFadeEdgeInsets; // @synthesize marqueeFadeEdgeInsets=_marqueeFadeEdgeInsets;
@property(readonly, nonatomic, getter=isMarqueeEnabled) _Bool marqueeEnabled; // @synthesize marqueeEnabled=_marqueeEnabled;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(copy, nonatomic) NSArray *attributedTexts; // @synthesize attributedTexts=_attributedTexts;
- (void).cxx_destruct;
- (void)_updateViewsIfNeeded;
- (void)_setupLabel:(inout id *)arg1 marqueeView:(inout id *)arg2 withAttributedText:(id)arg3;
- (void)_reloadVisualHighlightStateAnimated:(_Bool)arg1;
- (void)_layoutLabel:(id)arg1 withMarqueeView:(id)arg2 previousLabelBaselineOffsetFromBottom:(double)arg3 previousMarqueeViewFrame:(struct CGRect)arg4;
- (double)_baselineOffsetForAttributedText:(id)arg1 returningFont:(out id *)arg2;
- (void)_applyMarqueeFade;
- (void)resetMarqueePosition;
- (void)setMarqueeEnabled:(_Bool)arg1 withOptions:(long long)arg2;
@property(readonly, nonatomic) double firstBaselineOffsetFromTop;
- (void)setHighlighted:(_Bool)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

