//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIScrollingTabBarController.h>

@class MPAVController, MusicMiniPlayerViewController, MusicNowPlayingViewController;

@interface MusicTabBarController : SKUIScrollingTabBarController
{
    _Bool _isMiniPlayerPresented;
    _Bool _shouldIgnorePresentations;
    CDUnknownBlockType _nowPlayingPresentationCompletionHandler;
    _Bool _miniPlayerVisible;
    MPAVController *_player;
    MusicMiniPlayerViewController *_miniPlayerViewController;
    MusicNowPlayingViewController *_nowPlayingViewController;
}

@property(nonatomic, getter=isMiniPlayerVisible) _Bool miniPlayerVisible; // @synthesize miniPlayerVisible=_miniPlayerVisible;
@property(readonly, nonatomic) MusicNowPlayingViewController *nowPlayingViewController; // @synthesize nowPlayingViewController=_nowPlayingViewController;
@property(readonly, nonatomic) MusicMiniPlayerViewController *miniPlayerViewController; // @synthesize miniPlayerViewController=_miniPlayerViewController;
@property(retain, nonatomic) MPAVController *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)_updateMiniPlayerVisiblity;
- (void)_playerDidReloadWithPlaybackContextNotification:(id)arg1;
- (void)_playerContentsChangedNotification:(id)arg1;
- (void)setClientContext:(id)arg1;
- (void)presentNowPlayingViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentNowPlayingViewController;
- (void)dismissMiniPlayerViewController;
- (void)presentMiniPlayerViewController;
- (void)setTransientViewController:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealloc;

@end

