//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL;

@interface MusicStreamingItemAssetDescriptor : NSObject
{
    NSString *_downloadKey;
    NSString *_flavor;
    NSArray *_sinfs;
    NSURL *_URL;
}

@property(readonly, retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(readonly, copy, nonatomic) NSArray *sinfs; // @synthesize sinfs=_sinfs;
@property(readonly, copy, nonatomic) NSString *flavor; // @synthesize flavor=_flavor;
@property(readonly, copy, nonatomic) NSString *downloadKey; // @synthesize downloadKey=_downloadKey;
- (void).cxx_destruct;
- (id)description;
- (id)_initWithResponseDictionary:(id)arg1;

@end

