//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FuseUI/MusicEntityVerticalLockupView.h>

@class MusicNowPlayingFloatingButton, UIView;
@protocol MusicEntityEditableVerticalLockupViewDelegate;

@interface MusicEntityEditableVerticalLockupView : MusicEntityVerticalLockupView
{
    UIView *_artworkEditingOverlayView;
    MusicNowPlayingFloatingButton *_cameraButton;
    _Bool _editing;
}

@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
- (void).cxx_destruct;
- (void)_layoutEditingSubviewsForEditing:(_Bool)arg1 editingViewsAlpha:(double)arg2;
- (void)_layoutEditingSubviews;
- (void)_cameraButtonTapped:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)dealloc;

// Remaining properties
@property(nonatomic) __weak id <MusicEntityEditableVerticalLockupViewDelegate> delegate; // @dynamic delegate;

@end

