//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <FuseUI/MPURatingControlDelegate-Protocol.h>
#import <FuseUI/UIViewControllerTransitioningDelegate-Protocol.h>

@class MPAVItem, MusicNowPlayingRatingControl, NSString, UITextView, UIView, _UIBackdropView;

@interface MusicNowPlayingLyricsViewController : UIViewController <MPURatingControlDelegate, UIViewControllerTransitioningDelegate>
{
    _UIBackdropView *_backdropView;
    UITextView *_textView;
    MusicNowPlayingRatingControl *_ratingControl;
    UIView *_hairlineView;
    MPAVItem *_currentItem;
}

@property(retain, nonatomic) MPAVItem *currentItem; // @synthesize currentItem=_currentItem;
@property(readonly, nonatomic) UIView *hairlineView; // @synthesize hairlineView=_hairlineView;
@property(readonly, nonatomic) MusicNowPlayingRatingControl *ratingControl; // @synthesize ratingControl=_ratingControl;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
- (void).cxx_destruct;
- (void)_updateLyrics;
- (void)ratingDidChangeForRatingControl:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

