//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface MusicEntityProviderDownloadInformationController : NSObject
{
    NSObject<OS_dispatch_queue> *_calloutSerialQueue;
    struct MusicEntityDownloadInformation _lastDownloadInformation;
    struct vector<__weak id<MusicEntityProviderDownloadInformationControllerObserver>, std::__1::allocator<__weak id<MusicEntityProviderDownloadInformationControllerObserver>>> _observers;
    NSObject<OS_dispatch_queue> *_accessQueue;
    NSObject<OS_dispatch_queue> *_processingSerialQueue;
}

+ (struct MusicEntityDownloadInformation)_downloadInformationWithKeepLocalEntityCount:(unsigned long long)arg1 nonPurgeableEntityCount:(unsigned long long)arg2 relevantActiveDownloads:(id)arg3;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *processingSerialQueue; // @synthesize processingSerialQueue=_processingSerialQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_setDownloadInformation:(struct MusicEntityDownloadInformation)arg1;
- (void)_endGeneratingDownloadInformationChanges;
- (void)_beginGeneratingDownloadInformationChanges;
- (void)removeDownloadInformationObserver:(id)arg1;
- (void)getDownloadInformationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)addDownloadInformationObserver:(id)arg1;
@property(readonly, nonatomic) struct MusicEntityDownloadInformation lastDownloadInformation;
- (id)init;

@end

