//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface _MKPlacePhotosCell : UICollectionViewCell
{
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *imageView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

