//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKCustomSeparatorTableViewCell.h>

@class NSLayoutConstraint, NSString, UILabel;
@protocol _MKPlaceTransitIncidentCellDelegate;

__attribute__((visibility("hidden")))
@interface _MKPlaceTransitIncidentCell : MKCustomSeparatorTableViewCell
{
    UILabel *_messageLabel;
    NSLayoutConstraint *_messageToTopConstraint;
    id <_MKPlaceTransitIncidentCellDelegate> _delegate;
}

@property(nonatomic) __weak id <_MKPlaceTransitIncidentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *incidentMessage;
- (void)_buttonSelected;
- (void)didMoveToWindow;
- (void)_updateConstraintValues;
- (void)_contentSizeCategoryDidChange;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

