//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOComposedWaypoint.h>

@interface GEOComposedWaypoint (MKGeoServicesExtras)
+ (void)composedWaypointForMapItem:(id)arg1 forQuickETA:(_Bool)arg2 traits:(id)arg3 completionHandler:(CDUnknownBlockType)arg4 networkActivityHandler:(CDUnknownBlockType)arg5;
@end

