//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/NSObject-Protocol.h>

@class MKPlacePhotosViewController, NSString;

@protocol MKPlaceCardPhotosControllerDelegate <NSObject>

@optional
- (_Bool)shouldUseSmallPhotosWithPhotosController:(MKPlacePhotosViewController *)arg1;
- (void)placeCardPhotosControllerDidSelectViewAllPhotos:(MKPlacePhotosViewController *)arg1;
- (void)placeCardPhotosControllerDidSelectAddPhoto:(MKPlacePhotosViewController *)arg1;
- (void)placeCardPhotosController:(MKPlacePhotosViewController *)arg1 didSelectViewPhotoWithID:(NSString *)arg2;
@end

