//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AssistantServices/AFSessionObject-Protocol.h>

@class NSArray, NSString;

@interface AFSpeechPacket : NSObject <AFSessionObject>
{
    NSString *_aceId;
    NSString *_refId;
    NSArray *_packets;
    long long _packetNumber;
}

@property(nonatomic) long long packetNumber; // @synthesize packetNumber=_packetNumber;
@property(retain, nonatomic) NSArray *packets; // @synthesize packets=_packets;
@property(copy, nonatomic) NSString *refId; // @synthesize refId=_refId;
@property(copy, nonatomic) NSString *aceId; // @synthesize aceId=_aceId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)serializedAceDataError:(id *)arg1;
- (void)af_dispatchSendCompletionsWithResult:(long long)arg1 error:(id)arg2;
- (void)af_addSendCompletion:(CDUnknownBlockType)arg1;
- (_Bool)af_supportsSendCompletions;
- (void)af_logDiagnostics;
- (_Bool)af_bufferingAllowedDuringActiveSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

