//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SAObjects/SAMetrics.h>

@interface SAMetrics (AFSessionObject)
- (void)af_dispatchSendCompletionsWithResult:(long long)arg1 error:(id)arg2;
- (void)af_addSendCompletion:(CDUnknownBlockType)arg1;
- (_Bool)af_supportsSendCompletions;
@end

