//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKQuadTree : NSObject
{
    struct GKCQuadTree<NSObject> *_cQuadTree;
}

+ (id)quadTreeWithMinPosition:(float)arg1 maxPosition:minCellSize: /* Error: Ran out of types for this method. */;
- (_Bool)removeData:(id)arg1 withNode:(id)arg2;
- (_Bool)removeData:(id)arg1;
- (id)queryDataForQuad:quadSize: /* Error: Ran out of types for this method. */;
- (id)queryDataForPoint: /* Error: Ran out of types for this method. */;
- (id)addDataWithQuad:(id)arg1 quadOrigin:quadSize: /* Error: Ran out of types for this method. */;
- (id)addDataWithPoint:(id)arg1 point: /* Error: Ran out of types for this method. */;
- (void)dealloc;
- (id)initWithMinPosition:(float)arg1 maxPosition:minCellSize: /* Error: Ran out of types for this method. */;
- (id)init;

@end

