//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;

@interface MFFontMetricCache : NSObject
{
    NSString *_preferredSizeValidationKey;
    NSMutableDictionary *_metricCacheDictionary;
}

+ (id)sharedFontMetricCache;
- (void)_didReceivePreferredFontChangedNotification:(id)arg1;
- (_Bool)ensureCacheIsValid;
- (void)_invalidateCache;
- (double)cachedFloat:(CDUnknownBlockType)arg1 forKey:(id)arg2;
- (id)cachedFont:(CDUnknownBlockType)arg1 forKey:(id)arg2;
- (id)init;
- (void)dealloc;

@end

