//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MessageUI/NSObject-Protocol.h>

@class MFModernAddressAtom, NSString;

@protocol MFModernAddressAtomDelegate <NSObject>

@optional
- (void)addressAtom:(MFModernAddressAtom *)arg1 displayStringDidChange:(NSString *)arg2;
@end

