//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPAVItem, RadioStation;

@interface RUAddStationEpilogueContext : NSObject
{
    _Bool _shouldKeepPlayingCurrentItem;
    _Bool _shouldBeginPlayback;
    RadioStation *_addedStation;
    MPAVItem *_prefixItem;
}

@property(nonatomic) _Bool shouldBeginPlayback; // @synthesize shouldBeginPlayback=_shouldBeginPlayback;
@property(nonatomic) _Bool shouldKeepPlayingCurrentItem; // @synthesize shouldKeepPlayingCurrentItem=_shouldKeepPlayingCurrentItem;
@property(retain, nonatomic) MPAVItem *prefixItem; // @synthesize prefixItem=_prefixItem;
@property(readonly, nonatomic) RadioStation *addedStation; // @synthesize addedStation=_addedStation;
- (void).cxx_destruct;
- (id)description;
- (id)initWithAddedStation:(id)arg1;

@end

