//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RadioUI/RURadioAVItem.h>

@class NSString;

@interface RURadioTrackAVItem : RURadioAVItem
{
    NSString *_assetFlavor;
    NSString *_preferredAssetFlavor;
}

+ (id)_currentPreferredAssetFlavor;
- (void).cxx_destruct;
- (id)_sinfsByRemovingEmptyPinfsFromSinfs:(id)arg1;
- (void)_saveDownloadKeyCookie:(id)arg1 forURL:(id)arg2;
- (id)_bestRadioTrackAssetWithPreferredAssetFlavor:(id)arg1 availableAssets:(id)arg2;
- (id)assetFlavor;
- (_Bool)supportsRadioTrackActions;
- (void)loadAssetAndPlayerItem;
- (_Bool)isValidPlayerSubstituteForItem:(id)arg1;

@end

