//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface GEOLogMessageCacheManager : NSObject
{
    NSString *_logMessageCacheFilePath;
    struct sqlite3 *_logMessageCacheDatabase;
    NSString *_adaptorId;
    _Bool _fromLogFrameworkAdaptor;
    long long _logMessageCacheIterator;
    long long _logMessageCacheEndIterator;
    NSMutableArray *_retrivedLogMessageCacheIds;
    int _currentRetrivedLogMessageRetryCount;
    NSObject<OS_dispatch_queue> *_databaseQueue;
    void *_databaseQueueIdentityKey;
    void *_databaseQueueIdentityValue;
}

@property(readonly) int currentRetrivedLogMessageRetryCount; // @synthesize currentRetrivedLogMessageRetryCount=_currentRetrivedLogMessageRetryCount;
- (void)_updateLogMessageCacheDBUserVersion;
- (long long)_queryLogMessageCacheDBUserVersion;
- (void)_cleanupLogMessageCacheDatabase;
- (long long)_getNumberOfLogMessagesInCache;
- (long long)_retrieveEndLogMessageCacheIterator;
- (id)_groupIDOfNextPendingLogMessage;
- (id)_retrieveBatchOfLogMessagesLimitCount:(long long)arg1 limitSize:(long long)arg2;
- (void)_deleteAllExpiredLogMessages:(double)arg1;
- (void)_deleteExpiredLogMessageCacheDBFile:(double)arg1;
- (void)_addRetryCountColumnToTable;
- (void)_migrateDatabaseIfNeeded;
- (void)_createTables;
- (void)_executeSQL:(id)arg1;
- (void)_openCreateLogMessageCacheDBFile;
- (void)_openLogMessageCacheDBFile;
- (_Bool)_logMessageCacheFileExists;
- (_Bool)_usingInMemoryLogMessageCacheFile;
- (_Bool)isLogMessageCacheEmpty;
- (void)updateCurrentlyRetrievedLogMessagesRetryCount;
- (void)purgeCurrentlyRetrievedLogMessagesFromCache;
- (void)purgeExpiredLogMessagesFromCache:(double)arg1;
- (void)closeLogMessageCache;
- (id)retrieveNextBatchOfLogMessagesWithLimitCount:(long long)arg1 limitSize:(long long)arg2;
- (id)retrieveFirstBatchOfLogMessagesWithLimitCount:(long long)arg1 limitSize:(long long)arg2;
- (void)resetLogMessageCacheIterator;
- (void)insertLogMessageIntoCache:(id)arg1;
- (void)openLogMessageCache;
- (void)dealloc;
- (id)initWithLogMessageCacheFilePath:(id)arg1 adaptorId:(id)arg2 fromLogFrameworkAdaptor:(_Bool)arg3;

@end

