//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol OS_dispatch_queue;

@interface MPPlaybackUserDefaults : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    _Bool _allowsHighQualityMusicStreamingOnCellular;
    NSObject<OS_dispatch_queue> *_calloutQueue;
    struct vector<int, std::__1::allocator<int>> _notifyTokens;
}

+ (id)standardUserDefaults;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_addNotificationObserver:(CDUnknownBlockType)arg1 forUserDefaultKey:(struct __CFString *)arg2;
@property(readonly, nonatomic) _Bool allowsHighQualityMusicStreamingOnCellular;
- (void)dealloc;
- (id)init;

@end

