//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCActiveAppManager : NSObject
{
}

+ (void)removeActiveNotificationIdentifier:(id)arg1;
+ (void)addActiveNotificationIdentifier:(id)arg1;
+ (void)removeActiveGlanceIdentifier:(id)arg1;
+ (void)addActiveGlanceIdentifier:(id)arg1;

@end

