//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDateFormatter.h>

@interface FMRelativeDateFormatter : NSDateFormatter
{
}

- (id)stringForObjectValue:(id)arg1;
- (id)formattingContextKeyForKey:(id)arg1;
- (id)localizedStringForKey:(id)arg1;
- (id)init;

@end

