//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface CASlotProxy : NSObject
{
    struct Proxy *_proxy;
}

- (struct Object *)CA_copyRenderValue;
- (void)dealloc;
- (id)initWithName:(unsigned int)arg1;

@end

