//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NanoPassKit/PDXPCServiceExportedInterface-Protocol.h>

@class NPKPassLibraryFilter, NSString, NSXPCConnection;
@protocol OS_dispatch_queue;

@interface NPDPassLibrary : NSObject <PDXPCServiceExportedInterface>
{
    _Bool _serviceActive;
    NSXPCConnection *_connection;
    NPKPassLibraryFilter *_filter;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property _Bool serviceActive; // @synthesize serviceActive=_serviceActive;
@property(retain) NPKPassLibraryFilter *filter; // @synthesize filter=_filter;
@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)broadcastPassRemoved:(id)arg1;
- (void)broadcastPassUpdated:(id)arg1;
- (void)broadcastPassAdded:(id)arg1;
- (void)serviceSuspended;
- (void)serviceResumed;
- (id)initWithConnection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

