//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class _UIAlertControllerActionView;

__attribute__((visibility("hidden")))
@interface _UIAlertControllerCollectionViewCell : UICollectionViewCell
{
    _UIAlertControllerActionView *_actionView;
}

@property(retain, nonatomic) _UIAlertControllerActionView *actionView; // @synthesize actionView=_actionView;
- (void).cxx_destruct;
- (void)focusedViewDidChange;
- (id)focusedView;
- (id)preferredFocusedView;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;

@end

