//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _UIFocusSoundPool : NSObject
{
    unsigned int _originalID;
    NSArray *_queue;
    long long _index;
}

- (void).cxx_destruct;
- (void)playWithVolume:(double)arg1 pan:(double)arg2;
- (id)initWithSystemSoundID:(unsigned int)arg1;

@end

