//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UIKit/UIGestureRecognizerDelegate-Protocol.h>

@class CADisplayLink, NSArray, NSMapTable, NSString, NSTimer, UIMoveEvent, UIScrollView, UITapGestureRecognizer, UIView, UIWindow, _UIFocusEngineJoystickGestureRecognizer, _UIFocusEnginePanGestureRecognizer, _UIFocusPressGestureRecognizer, _UIFocusSoundPool, _UIFocusTouchDebugView;
@protocol OS_dispatch_queue, _UIFocusScrollAnimator;

@interface _UIFocusEngine : NSObject <UIGestureRecognizerDelegate>
{
    _UIFocusEnginePanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    _UIFocusPressGestureRecognizer *_selectGestureRecognizer;
    struct CGPoint _touchBeganPoint;
    struct CGPoint _lastKnownTouchPoint;
    struct CGVector _progressAccumulator;
    id <_UIFocusScrollAnimator> _scrollViewAnimator;
    struct CGPoint _firstMomentumTouchPoint;
    struct CGPoint _lastMomentumTouchPoint;
    struct CGPoint _momentumVelocity;
    double _momentumFriction;
    unsigned long long _focusUpdateCountSinceLastPanBegan;
    CADisplayLink *_momentumDisplayLink;
    NSArray *_remoteGestures;
    _UIFocusEngineJoystickGestureRecognizer *_joystickGestureRecognizer;
    NSTimer *_joystickModeExitTimer;
    NSTimer *_joystickModeRepeatTimer;
    double _previousJoystickFocusMovementTime;
    double _previousJoystickRegionEntryTime;
    unsigned long long _joystickRepeatingHeading;
    CADisplayLink *_joystickFocusDirectionDisplayLink;
    struct CGPoint _currentFocusDirection;
    NSMapTable *_focusRollbackAnimations;
    UIScrollView *_peekingScrollView;
    struct CGSize _peekingScrollViewPeekSize;
    unsigned long long _peekingHeading;
    NSMapTable *_cachedViewSearchResults;
    NSObject<OS_dispatch_queue> *_soundQueue;
    _UIFocusSoundPool *_smallSoundPool;
    _UIFocusSoundPool *_largeSoundPool;
    _UIFocusSoundPool *_appIconSoundPool;
    _UIFocusSoundPool *_keyboardSoundPool;
    unsigned long long _currentGestureID;
    UIScrollView *_lastScrolledScroll;
    double _lastEdgeScrollEdgeValue;
    _UIFocusTouchDebugView *_touchIndicatorView;
    NSMapTable *_activeScrollViewLoadingBounds;
    NSMapTable *_activeScrollViewAnimatingBounds;
    unsigned long long _inputType;
    struct {
        unsigned int isSettingFocusedView:1;
        unsigned int isEligibleToCrossSpeedBump:1;
        unsigned int isContinuingTouchWithMomentum:1;
        unsigned int isAnimatingFocusDirectionRollback:1;
        unsigned int isPerformingJoystickRollback:1;
        unsigned int isJoystickInRepeatMode:1;
        unsigned int isPendingJoystickRepeat:1;
        unsigned int isPeekingScrollView:1;
        unsigned int shouldApplyAcceleration:1;
        unsigned int shouldShowDebugOverlays:1;
    } _flags;
    _Bool _enabled;
    _Bool _wantsScrollPeeking;
    _Bool _shouldShowDebugOverlays;
    _Bool _sendsFocusDirection;
    _Bool _playsSoundOnFocusChange;
    UIWindow *_targetWindow;
    UIView *_viewForTouchDeferredFocus;
    UIMoveEvent *_moveEvent;
}

@property(nonatomic, getter=_playsSoundOnFocusChange, setter=_setPlaysSoundOnFocusChange:) _Bool playsSoundOnFocusChange; // @synthesize playsSoundOnFocusChange=_playsSoundOnFocusChange;
@property(nonatomic, getter=_sendsFocusDirection, setter=_setSendsFocusDirection:) _Bool sendsFocusDirection; // @synthesize sendsFocusDirection=_sendsFocusDirection;
@property(retain, nonatomic) UIMoveEvent *moveEvent; // @synthesize moveEvent=_moveEvent;
@property(nonatomic) _Bool shouldShowDebugOverlays; // @synthesize shouldShowDebugOverlays=_shouldShowDebugOverlays;
@property(nonatomic) __weak UIView *viewForTouchDeferredFocus; // @synthesize viewForTouchDeferredFocus=_viewForTouchDeferredFocus;
@property(nonatomic) __weak UIWindow *targetWindow; // @synthesize targetWindow=_targetWindow;
@property(nonatomic) _Bool wantsScrollPeeking; // @synthesize wantsScrollPeeking=_wantsScrollPeeking;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
@property(readonly, nonatomic) double _animationCoefficient;
- (id)_closestFocusableViewToPoint:(struct CGPoint)arg1 inView:(id)arg2;
- (id)_closestFocusableViewToRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)_updateDebugOverlayByRemovingTouchIndicators;
- (void)_updateDebugOverlayWithTouchAtNormalizedPoint:(struct CGPoint)arg1 navigationBoundary:(struct CGRect)arg2;
- (void)_teardownDebugOverlays;
- (void)_setupDebugOverlays;
- (void)_sendGestureEndNotification;
- (void)_sendGestureBeginNotification;
- (void)_sendFocusDirectionNotificationWithDirection:(struct CGPoint)arg1;
- (void)_ensureFocusedViewIsOnscreen:(id)arg1;
- (struct CGPoint)_contentOffsetForScrollView:(id)arg1 toFocusView:(id)arg2;
- (struct CGPoint)_contentOffsetForScrollView:(id)arg1 toFocusView:(id)arg2 targetOffset:(struct CGPoint)arg3 targetBounds:(struct CGRect)arg4;
- (void)_scrollView:(id)arg1 toOffset:(struct CGPoint)arg2;
- (void)_performScrollingIfNeededForFocusUpdateContext:(id)arg1;
- (void)_sendMomentumEndNotificationsAndAnimateRollback:(_Bool)arg1;
- (void)_stopMomentumAndPerformRollback;
- (_Bool)_shouldPerformFocusUpdateWithCurrentMomentumStatus;
- (void)_momentumHeartbeat:(id)arg1;
- (void)_continueTouchWithMomentum;
- (double)_frictionInterpolationForMomentumSpeed:(double)arg1 totalDistance:(double)arg2 slope:(double)arg3 shortDistance:(double)arg4 longDistance:(double)arg5;
- (double)_verticalFrictionInterpolationForMomentumSpeed:(double)arg1 totalDistance:(double)arg2;
- (double)_horizontalFrictionInterpolationForMomentumSpeed:(double)arg1 totalDistance:(double)arg2;
- (void)_recordMomentumForPoint:(struct CGPoint)arg1;
- (void)_resetMomentum;
- (void)_resetFocusDirectionRollbackForAllViews;
- (void)_resetFocusDirectionRollbackForView:(id)arg1;
- (void)_startFocusDirectionRollbackForView:(id)arg1;
- (id)_scrollViewToPeekStartingAtFocusedView:(id)arg1 focusHeading:(unsigned long long)arg2;
- (void)_peekScrollViewStartingAtFocusedView:(id)arg1 progress:(struct CGVector)arg2;
- (void)_resetScrollViewPeek:(_Bool)arg1;
- (void)_resetJoystick;
- (void)_joystickDisplayLinkHeartbeat:(id)arg1;
- (unsigned long long)_headingForJoystickPosition:(struct CGPoint)arg1 usingMinimumRadius:(double)arg2;
- (struct CGVector)_joystickVelocityForHeading:(unsigned long long)arg1 timeInMovementZone:(double)arg2;
- (double)_joystickRepeatDurationForTimeInMovementZone:(double)arg1;
- (void)_joystickPerformRepeat:(id)arg1;
- (_Bool)_joystickAttemptToMoveAlongHeading:(unsigned long long)arg1 withVelocity:(struct CGVector)arg2;
- (void)_handleJoystickTiltMode:(id)arg1;
- (void)_handleJoystickRepeatMode:(id)arg1;
- (void)_exitJoystickModeForReal:(id)arg1;
- (void)_joystickGestureEnded:(id)arg1;
- (void)_joystickGestureUpdated:(id)arg1;
- (void)_joystickGestureBegan:(id)arg1;
- (_Bool)_attemptToMoveFocusAlongHeading:(unsigned long long)arg1 reportedVelocity:(struct CGVector)arg2 startingView:(id)arg3;
- (void)_panGestureEnd:(id)arg1;
- (void)_updatePanLocation:(struct CGPoint)arg1 reportedVelocity:(struct CGVector)arg2 wantsFocusDirection:(_Bool)arg3;
- (void)_panGestureStart:(id)arg1;
- (_Bool)_wouldCrossSpeedBumpWhenMovingAlongHeading:(unsigned long long)arg1 fromView:(id)arg2 toView:(id)arg3;
- (_Bool)_speedBumpsAllowFocusToMoveAlongHeading:(unsigned long long)arg1;
- (_Bool)_wouldCrossSpeedBumpWhenMovingAlongHeading:(unsigned long long)arg1;
- (double)_effortRequiredToMoveAlongHeading:(unsigned long long)arg1;
- (void)_setCachedSearchResult:(id)arg1 forHeading:(unsigned long long)arg2;
- (id)_cachedSearchResultForHeading:(unsigned long long)arg1;
- (void)_resetViewSearchCache;
- (void)_loadScrollViewContentAlongHeading:(unsigned long long)arg1 fromView:(id)arg2;
- (void)_clearVisibleRectForLoadingScrollViewContent:(id)arg1;
- (void)_setVisibleRect:(struct CGRect)arg1 forLoadingScrollViewContent:(id)arg2;
- (void)_removeVisibleRect:(struct CGRect)arg1 fromScrollViewForAnimation:(id)arg2;
- (void)_addVisibleRect:(struct CGRect)arg1 toScrollViewForAnimation:(id)arg2;
- (struct CGRect)_visibleBoundsForScrollView:(id)arg1;
- (void)_animateOffsetOfScrollView:(id)arg1 toShowFocusedView:(id)arg2;
- (struct CGPoint)_targetContentOffsetForScrollView:(id)arg1;
- (void)_cancelScrollingForScrollView:(id)arg1;
- (_Bool)_isScrollingScrollView:(id)arg1;
- (_Bool)_isContinuingTouchWithMomentum;
- (struct CGRect)_minimumSearchAreaForContainerView:(id)arg1;
- (_Bool)_updateFocusedViewAndScroll:(id)arg1 withSoundVolume:(double)arg2;
- (_Bool)_moveFocusAlongHeading:(unsigned long long)arg1 withVelocity:(struct CGVector)arg2;
- (struct CGSize)_touchSensitivityForView:(id)arg1;
- (id)_bestFocusCandidateForFocusHeading:(unsigned long long)arg1 currentFocusView:(id)arg2 direction:(struct CGVector)arg3;
- (id)_bestFocusCandidateStartingAtView:(id)arg1 focusHeading:(unsigned long long)arg2;
- (id)_noCache_bestFocusCandidateStartingAtView:(id)arg1 focusHeading:(unsigned long long)arg2;
- (id)_findFocusCandidateByExhaustivelySearchingScrollView:(id)arg1 focusHeading:(unsigned long long)arg2 startingView:(id)arg3;
- (_Bool)_shouldRecordDestinationViewDistanceOffscreen;
- (_Bool)_shouldEagerlyValidateFocusCandidates;
- (id)_findFocusCandidateStartingInRegionWithoutLoadingScrollViewContent:(id)arg1 focusHeading:(unsigned long long)arg2 startingView:(id)arg3 minimumSearchArea:(struct CGRect)arg4;
- (_Bool)_updateFocusWithContext:(id)arg1;
- (int)_touchRegionForDigitizerLocation:(struct CGPoint)arg1;
- (void)_removeGestureRecognizers;
- (void)_addGestureRecognizers;
- (id)_panGestureRecognizer;
- (void)_setPanGestureRecognizer:(id)arg1;
- (id)_focusedView;
- (id)_poolForFocusSound:(long long)arg1;
- (id)_soundQueue;
- (void)_playFocusSound:(long long)arg1 withPan:(double)arg2 volume:(double)arg3;
- (void)_cleanUpSounds;
- (void)_setUpSounds;
- (void)_gestureRecognizerFailed:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_handleJoystickGesture:(id)arg1;
- (void)_sendDelayedPressEventWithType:(long long)arg1 timestamp:(double)arg2;
- (void)_handleTapGesture:(id)arg1;
- (void)_handlePanGesture:(id)arg1;
- (void)_handleButtonGesture:(id)arg1;
- (void)_handleSelectGesture:(id)arg1;
- (void)reset;
- (id)viewForFocusHeading:(unsigned long long)arg1 fromView:(id)arg2;
- (_Bool)moveInDirection:(unsigned long long)arg1;
- (_Bool)moveWithEvent:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)_runPerformanceTestWithName:(id)arg1 bySwipingAlongAxis:(int)arg2;
- (void)_runPerformanceTestWithName:(id)arg1 fakeEvents:(CDStruct_37aeb80e *)arg2 count:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

