//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIWindow;

@interface _UIModalItemAppViewController : UIViewController
{
    UIWindow *_rotationDelegate;
}

@property(retain, nonatomic) UIWindow *rotationDelegate; // @synthesize rotationDelegate=_rotationDelegate;
- (_Bool)shouldAutorotate;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;

@end

