//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UINavigationBarPhonePadVisualStyle.h>

__attribute__((visibility("hidden")))
@interface _UINavigationBarLegacyVisualStyle : _UINavigationBarPhonePadVisualStyle
{
}

- (double)buttonImagePadding;
- (double)minBackTextWidth;
- (double)maxBackButtonProportion;
- (double)interBlockSpace;
- (double)rightTitleMargin;
- (double)leftEdgeMargin;
- (id)buttonFontForStyle:(long long)arg1;
- (double)leftTitleMargin;
- (double)buttonFontSize;
- (double)headingFontSize;
- (double)backButtonAnimationClippingPadding;

@end

