//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (UIAccessibilityPrivate)
+ (void)__accessibilityRequestGuidedAccessSession:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
+ (long long)__accessibilityGuidedAccessRestrictionStateForIdentifier:(id)arg1;
+ (_Bool)__accessibilityGuidedAccessStateEnabled;
- (void)_accessibilityFinalize;
- (void)accessibilitySetIdentification:(id)arg1;
@end

