//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertControllerVisualStyleAlert.h>

__attribute__((visibility("hidden")))
@interface UIAlertControllerVisualStyleAlertTV : UIAlertControllerVisualStyleAlert
{
}

- (double)textFieldHorizontalMargin;
- (struct UIEdgeInsets)textFieldCollectionViewContentInset;
- (id)motionEffects;
- (struct UIEdgeInsets)collectionViewContentInsets;
- (struct UIEdgeInsets)collectionViewGradientMaskInsets;
- (struct CATransform3D)highlightedActionTransformForActionSize:(struct CGSize)arg1;
- (void)animateAlertControllerView:(id)arg1 ofAlertController:(id)arg2 forPresentation:(_Bool)arg3 inContainerView:(id)arg4 descendantOfContainerView:(id)arg5 duration:(double)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (double)transitionDurationForPresentation:(_Bool)arg1 ofAlertController:(id)arg2;
- (id)dimmingViewForAlertController:(id)arg1;
- (struct CGSize)collectionViewOutsetSize;
- (_Bool)actionContentInheritsTextColor;
- (_Bool)actionLabelsMayUseMarqueeWhenFocused;
- (_Bool)actionLabelsMayAdjustFontsToFit;
- (double)sectionDelimitingSeparatorDimension;
- (_Bool)hideActionSeparators;
- (_Bool)hideCancelAction:(id)arg1 inAlertController:(id)arg2;
- (long long)permittedActionLayoutDirection;
- (id)textFieldContainingViewWithTextField:(id)arg1;
- (id)backgroundViewForAction:(id)arg1 withViewRepresentation:(id)arg2 inAlertController:(id)arg3;
- (id)backgroundView;
- (double)backgroundCornerRadius;
- (struct UIEdgeInsets)contentInsets;
- (struct UIEdgeInsets)actionImageMarginForAction:(id)arg1 withViewRepresentation:(id)arg2 inAlertController:(id)arg3;
- (double)minimumActionHeight;
- (double)actionHorizontalContentMargin;
- (double)actionWidthForMinimumActionWidth:(double)arg1;
- (double)maximumWidthForTitleAndMessageContentView;
- (double)maximumWidth;
- (double)_maximumContentWidth;
- (double)_minimumButtonWidth;
- (double)_visualHorizontalInsetFromCellBounds;
- (long long)maximumNumberOfLinesInMessageLabel;
- (long long)maximumNumberOfLinesInTitleLabel;
- (double)marginAboveMessageLabelFirstBaseline;
- (double)marginBelowMessageLabelLastBaseline;
- (double)marginBelowLastLabelLastBaseline;
- (double)marginBelowTitleLabelLastBaseline;
- (double)marginAboveTitleLabelFirstBaseline;
- (id)actionContentColorForAction:(id)arg1 withViewRepresentation:(id)arg2 inAlertController:(id)arg3;
- (id)messageLabelColor;
- (double)_marginAboveDetailMessageFirstBaseline;
- (id)_detailMessageFont;
- (id)preferredActionFont;
- (id)regularActionFont;
- (id)messageLabelFont;
- (id)titleLabelColor;
- (id)titleLabelFont;

@end

