//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDictationView.h>

__attribute__((visibility("hidden")))
@interface UIDictationiPadLayoutView : UIDictationView
{
}

- (_Bool)isShowing;
- (void)returnToKeyboard;
- (void)finishReturnToKeyboard;
- (void)layoutSubviews;
- (void)setState:(int)arg1;
- (void)setRenderConfig:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

