//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKBRenderFactoryiPadHWR_Portrait.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactoryiPadHWR_Landscape : UIKBRenderFactoryiPadHWR_Portrait
{
}

- (double)controlColumnWidthFactor;
- (double)keyCornerRadius;
- (struct CGPoint)spaceReturnKeyTextOffset;
- (struct CGPoint)dismissKeyOffset;
- (double)dismissKeyFontSize;
- (double)spaceKeyFontSize;
- (double)dictationKeyFontSize;
- (double)internationalKeyFontSize;
- (double)moreKeyFontSize;
- (double)deleteKeyFontSize;

@end

