//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertController.h>

@protocol UIKBAlertControllerDelegate;

__attribute__((visibility("hidden")))
@interface UIKBAlertController : UIAlertController
{
    id <UIKBAlertControllerDelegate> _kbDelegate;
}

@property(nonatomic) id <UIKBAlertControllerDelegate> kbDelegate; // @synthesize kbDelegate=_kbDelegate;
- (void)viewDidDisappear:(_Bool)arg1;

@end

