//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIStatusBarItemView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface UIStatusBarPersonNameItemView : UIStatusBarItemView
{
    NSString *_personNameString;
    double _letterSpacing;
    double _maxWidth;
}

- (void).cxx_destruct;
- (long long)legibilityStyle;
- (double)addContentOverlap:(double)arg1;
- (double)resetContentOverlap;
- (id)contentsImage;
- (_Bool)_updateWithPersonName:(id)arg1 maxWidth:(double)arg2;
- (_Bool)updateForNewData:(id)arg1 actions:(int)arg2;
- (double)standardPadding;

@end

