//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, NSURL;

@protocol PRSBuyButton
@property(retain, nonatomic) NSURL *url;

@optional
@property(retain, nonatomic) NSString *offer_type;
@property(retain, nonatomic) NSString *adam_id;
@property(retain, nonatomic) NSString *subtitle;
@property(retain, nonatomic) NSString *title;
@end

