//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface PLImageLoadingUtilities : NSObject
{
}

+ (id)preheatItemSourceForFormatID:(int)arg1;
+ (id)_filledHalfScreenLargeImageLoader;
+ (id)_filledScreenLargeImageLoader;
+ (id)_fullScreenLargeImageLoader;
+ (id)_fullSizeLargeImageLoaderForFormatID:(int)arg1;
+ (id)newImageForAsset:(id)arg1 withFormat:(int)arg2 allowPlaceholder:(_Bool)arg3 outImageProperties:(const struct __CFDictionary **)arg4 outDeliveredPlaceholder:(_Bool *)arg5;
+ (id)newImageForAsset:(id)arg1 withFormat:(int)arg2 allowPlaceholder:(_Bool)arg3 optimalSourcePixelSize:(struct CGSize)arg4 networkAccessAllowed:(_Bool)arg5 networkAccessForced:(_Bool)arg6 trackCPLDownload:(_Bool)arg7 outImageProperties:(const struct __CFDictionary **)arg8 outImageDataInfo:(id *)arg9 outCPLDownloadContext:(id *)arg10;
+ (void)imageForAsset:(id)arg1 withFormat:(int)arg2 allowPlaceholder:(_Bool)arg3 optimalSourcePixelSize:(struct CGSize)arg4 networkAccessAllowed:(_Bool)arg5 networkAccessForced:(_Bool)arg6 trackCPLDownload:(_Bool)arg7 completion:(CDUnknownBlockType)arg8 sync:(_Bool)arg9;
+ (void)_assetsdImageForAsset:(id)arg1 withFormat:(id)arg2 allowPlaceholder:(_Bool)arg3 optimalSourcePixelSize:(struct CGSize)arg4 networkAccessAllowed:(_Bool)arg5 trackCPLDownload:(_Bool)arg6 sync:(_Bool)arg7 completion:(CDUnknownBlockType)arg8;
+ (id)newImageDataForAsset:(id)arg1 withFormat:(int)arg2 allowPlaceholder:(_Bool)arg3 wantURLOnly:(_Bool)arg4 networkAccessAllowed:(_Bool)arg5 networkAccessForced:(_Bool)arg6 trackCPLDownload:(_Bool)arg7 outImageDataInfo:(id *)arg8 outCPLDownloadContext:(id *)arg9;
+ (_Bool)canAccessImageForAsset:(id)arg1;

@end

