//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaRemote/MRProtocolMessage.h>

@interface MRAuthenticationResponseMessage : MRProtocolMessage
{
}

- (unsigned long long)type;
- (_Bool)requiresAuthentication;
@property(readonly, nonatomic) unsigned long long credentialRequirementCharacterCount;
@property(readonly, nonatomic) unsigned int credentialRequirementType;
- (id)authToken;
- (id)initWithCredentialRequirementType:(unsigned int)arg1 characterCount:(unsigned long long)arg2;
- (id)initWithAuthenticationToken:(id)arg1;

@end

