//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GCController, MRGameControllerDaemonProxy;

@interface MREmulatedGameController : NSObject
{
    GCController *_controller;
    MRGameControllerDaemonProxy *_remote;
    int _profile;
    unsigned long long _controllerID;
}

@property(readonly, nonatomic) unsigned long long controllerID; // @synthesize controllerID=_controllerID;
@property(readonly, nonatomic) int profile; // @synthesize profile=_profile;
- (void)sendGameControllerEvent:(CDStruct_9f528be3 *)arg1;
- (void)dealloc;
- (id)initWithProfile:(int)arg1;

@end

