//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaRemote/MRProtocolMessage.h>

@class MRTextEditingAttributes, NSString;

@interface MRKeyboardMessage : MRProtocolMessage
{
    MRTextEditingAttributes *_attributes;
}

- (unsigned long long)type;
@property(readonly, nonatomic) MRTextEditingAttributes *attributes;
@property(readonly, nonatomic) NSString *text;
@property(readonly, nonatomic) unsigned long long state;
- (void)dealloc;
- (id)initWithState:(unsigned long long)arg1 text:(id)arg2 attributes:(id)arg3;

@end

