//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <MediaRemote/NSSecureCoding-Protocol.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface MRPlaybackQueue : NSObject <NSSecureCoding>
{
    NSArray *_contentItems;
    CDStruct_627e0f85 _range;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSArray *contentItems; // @synthesize contentItems=_contentItems;
@property(readonly, nonatomic) CDStruct_627e0f85 range; // @synthesize range=_range;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithContentItems:(id)arg1 range:(CDStruct_627e0f85)arg2;

@end

