//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface CATDispatchTimer : NSObject
{
    NSObject<OS_dispatch_queue> *mQueue;
    NSObject<OS_dispatch_queue> *mDelegateQueue;
    NSObject<OS_dispatch_source> *mTimerSource;
    id mTarget;
    SEL mSelector;
    unsigned long long mCallingOutSelector;
    NSDate *_fireDate;
    id _userInfo;
    double _timeInterval;
    double _tolerance;
}

+ (id)new;
@property double tolerance; // @synthesize tolerance=_tolerance;
@property double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(readonly, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)fire;
- (void)updateTimerFireDate:(id)arg1;
- (void)performFire;
- (void)invalidate;
- (void)dealloc;
- (id)initWithFireDate:(id)arg1 interval:(double)arg2 target:(id)arg3 selector:(SEL)arg4 userInfo:(id)arg5 repeats:(_Bool)arg6 queue:(id)arg7;
- (id)init;
@property(retain) NSDate *fireDate; // @synthesize fireDate=_fireDate;
@property(readonly, nonatomic, getter=isValid) _Bool valid;

@end

