//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosPlayer/_ISTargetView.h>

@class NSString, UIColor, UILabel, UIView;

@interface _ISPlayerDebugView : _ISTargetView
{
    UILabel *_label;
    UIView *_crosshairHorizontalLineView;
    UIView *_crosshairVerticalLineView;
    NSString *_text;
    double _crosshairRelativePosition;
    UIColor *_crosshairColor;
}

@property(retain, nonatomic) UIColor *crosshairColor; // @synthesize crosshairColor=_crosshairColor;
@property(nonatomic) double crosshairRelativePosition; // @synthesize crosshairRelativePosition=_crosshairRelativePosition;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

