//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class AVAsset;

@interface ISCrossfadeChefOperation : NSOperation
{
    int _photoEXIFOrientation;
    AVAsset *_videoAsset;
    double _crossfadeDuration;
    double _sourceStartTime;
    id _stillPhoto;
    unsigned long long _numberOfFrames;
    CDUnknownBlockType _resultHandler;
    struct CGSize _targetSize;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(readonly, nonatomic) struct CGSize targetSize; // @synthesize targetSize=_targetSize;
@property(readonly, nonatomic) unsigned long long numberOfFrames; // @synthesize numberOfFrames=_numberOfFrames;
@property(readonly, nonatomic) int photoEXIFOrientation; // @synthesize photoEXIFOrientation=_photoEXIFOrientation;
@property(retain, nonatomic) id stillPhoto; // @synthesize stillPhoto=_stillPhoto;
@property(readonly, nonatomic) double sourceStartTime; // @synthesize sourceStartTime=_sourceStartTime;
@property(readonly, nonatomic) double crossfadeDuration; // @synthesize crossfadeDuration=_crossfadeDuration;
@property(readonly, nonatomic) AVAsset *videoAsset; // @synthesize videoAsset=_videoAsset;
- (void).cxx_destruct;
- (id)initWithVideoAsset:(id)arg1 sourceStartTime:(double)arg2 stillPhoto:(struct CGImage *)arg3 photoEXIFOrientation:(int)arg4 crossfadeDuration:(double)arg5 numberOfFrames:(unsigned long long)arg6 targetSize:(struct CGSize)arg7 resultHandler:(CDUnknownBlockType)arg8;

@end

