//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVPlayer.h>

@interface ISFilteredAVPlayer : AVPlayer
{
    _Bool _filterEnabled;
    float _filterSweepValue;
}

@property(nonatomic) float filterSweepValue; // @synthesize filterSweepValue=_filterSweepValue;
@property(nonatomic, getter=isFilterEnabled) _Bool filterEnabled; // @synthesize filterEnabled=_filterEnabled;
- (void)_updateAudioMix;
- (void)replaceCurrentItemWithPlayerItem:(id)arg1;

@end

