//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosPlayer/ISSettings.h>

@interface ISPlayerSettings : ISSettings
{
    _Bool _useDedicatedQueues;
    _Bool _allowFrameBlending;
    _Bool _allowVideoPreRoll;
    _Bool _allowPlayerReuse;
    _Bool _allowCrossfadeContent;
    _Bool _shouldPauseOnSettle;
    _Bool _variableIntro;
    _Bool _assumeCroppedVideo;
    double _forceTouchTimeoutInterval;
    double _forceTouchTimeoutMinimumProgress;
    double _forceScrubMinimumPressure;
    double _forceScrubMaximumPressure;
    double _forceScrubRewindFactor;
    double _forceScrubMinRateChange;
    double _forceScrubSettleRateAddition;
    double _forceScrubMinimumRate;
    double _forceScrubMaximumInteractiveRate;
    double _audioRampDuration;
    double _crossfadeTargetBlur;
    double _crossfadeDuration;
    double _maxPreCrossfadeDuration;
    double _nonForcePreCrossfadeDuration;
}

+ (id)settingsControllerModule;
+ (id)sharedInstance;
@property(nonatomic) _Bool assumeCroppedVideo; // @synthesize assumeCroppedVideo=_assumeCroppedVideo;
@property(nonatomic) _Bool variableIntro; // @synthesize variableIntro=_variableIntro;
@property(nonatomic) double nonForcePreCrossfadeDuration; // @synthesize nonForcePreCrossfadeDuration=_nonForcePreCrossfadeDuration;
@property(nonatomic) double maxPreCrossfadeDuration; // @synthesize maxPreCrossfadeDuration=_maxPreCrossfadeDuration;
@property(nonatomic) double crossfadeDuration; // @synthesize crossfadeDuration=_crossfadeDuration;
@property(nonatomic) double crossfadeTargetBlur; // @synthesize crossfadeTargetBlur=_crossfadeTargetBlur;
@property(nonatomic) double audioRampDuration; // @synthesize audioRampDuration=_audioRampDuration;
@property(nonatomic) double forceScrubMaximumInteractiveRate; // @synthesize forceScrubMaximumInteractiveRate=_forceScrubMaximumInteractiveRate;
@property(nonatomic) double forceScrubMinimumRate; // @synthesize forceScrubMinimumRate=_forceScrubMinimumRate;
@property(nonatomic) double forceScrubSettleRateAddition; // @synthesize forceScrubSettleRateAddition=_forceScrubSettleRateAddition;
@property(nonatomic) double forceScrubMinRateChange; // @synthesize forceScrubMinRateChange=_forceScrubMinRateChange;
@property(nonatomic) double forceScrubRewindFactor; // @synthesize forceScrubRewindFactor=_forceScrubRewindFactor;
@property(nonatomic) double forceScrubMaximumPressure; // @synthesize forceScrubMaximumPressure=_forceScrubMaximumPressure;
@property(nonatomic) double forceScrubMinimumPressure; // @synthesize forceScrubMinimumPressure=_forceScrubMinimumPressure;
@property(nonatomic) double forceTouchTimeoutMinimumProgress; // @synthesize forceTouchTimeoutMinimumProgress=_forceTouchTimeoutMinimumProgress;
@property(nonatomic) double forceTouchTimeoutInterval; // @synthesize forceTouchTimeoutInterval=_forceTouchTimeoutInterval;
@property(nonatomic) _Bool shouldPauseOnSettle; // @synthesize shouldPauseOnSettle=_shouldPauseOnSettle;
@property(nonatomic) _Bool allowCrossfadeContent; // @synthesize allowCrossfadeContent=_allowCrossfadeContent;
@property(nonatomic) _Bool allowPlayerReuse; // @synthesize allowPlayerReuse=_allowPlayerReuse;
@property(nonatomic) _Bool allowVideoPreRoll; // @synthesize allowVideoPreRoll=_allowVideoPreRoll;
@property(nonatomic) _Bool allowFrameBlending; // @synthesize allowFrameBlending=_allowFrameBlending;
@property(nonatomic) _Bool useDedicatedQueues; // @synthesize useDedicatedQueues=_useDedicatedQueues;
- (void)setDefaultValues;

@end

