//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISWrappedAVPlayer;
@protocol ISVideoVolumeControllerDelegate;

@interface ISVideoVolumeController : NSObject
{
    struct {
        _Bool respondsToVolumeDidChange;
    } _delegateFlags;
    float __volumeRampStartValue;
    float __targetVolume;
    ISWrappedAVPlayer *_player;
    id <ISVideoVolumeControllerDelegate> _delegate;
    long long __volumeRampRequestNumber;
    double __volumeRampStartTime;
    double __volumeRampDuration;
}

@property(nonatomic, setter=_setTargetVolume:) float _targetVolume; // @synthesize _targetVolume=__targetVolume;
@property(nonatomic, setter=_setVolumeRampDuration:) double _volumeRampDuration; // @synthesize _volumeRampDuration=__volumeRampDuration;
@property(nonatomic, setter=_setVolumeRampStartValue:) float _volumeRampStartValue; // @synthesize _volumeRampStartValue=__volumeRampStartValue;
@property(nonatomic, setter=_setVolumeRampStartTime:) double _volumeRampStartTime; // @synthesize _volumeRampStartTime=__volumeRampStartTime;
@property(nonatomic, setter=_setVolumeRampRequestNumber:) long long _volumeRampRequestNumber; // @synthesize _volumeRampRequestNumber=__volumeRampRequestNumber;
@property(nonatomic) __weak id <ISVideoVolumeControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak ISWrappedAVPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)_tickRampVolumeWithRampRequestNumber:(long long)arg1;
- (void)setVolume:(float)arg1 withRampDuration:(double)arg2;
@property(nonatomic) float volume;
- (id)initWithPlayer:(id)arg1;

@end

