//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMFoundation/IMMessageItem.h>

@interface IMMessageItem (IMChat_Internal)
+ (Class)contextClass;
- (id)_copyWithFlags:(unsigned long long)arg1;
- (id)_copy;
- (_Bool)_isInvitation;
- (void)_setInivtation:(_Bool)arg1;
- (id)message;
@end

