//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BRCAccountSession, NSString;
@protocol BRCAccountHandlerDelegate, OS_dispatch_queue;

@interface BRCAccountHandler : NSObject
{
    BRCAccountSession *_session;
    NSString *_currentAccountID;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_migrationStatusSetterQueue;
    _Bool _hasSetMigrationComplete;
    id <BRCAccountHandlerDelegate> _delegate;
}

+ (id)primaryiCloudAccountID;
+ (id)primaryiCloudAccount;
+ (id)icloudDriveAccountID;
+ (void)_migrateAccountIfNecessaryForAccountID:(id)arg1;
@property(readonly, nonatomic) BRCAccountSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <BRCAccountHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)markMigrationCompletedForDSID:(id)arg1;
- (void)setMigrationStatus:(BOOL)arg1 forDSID:(id)arg2 shouldUpdateAccount:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)createCurrentAccountSessionWithID:(id)arg1 error:(id *)arg2;
- (void)destroyCurrentSessionSynchronously;
- (void)_updateAccountToAccountID:(id)arg1;
- (void)_handleAccountDidChange;
- (void)_handleAccountWillChange;
- (_Bool)_createCurrentAccountSessionWithID:(id)arg1 error:(id *)arg2;
- (_Bool)_loadCurrentOnDiskAccountSessionWithError:(id *)arg1;
- (void)_destroyCurrentSessionSynchronously;
- (void)jetsamCloudDocsApps;
- (void)startAndLoadCurrentAccountSynchronously;
- (void)_cleanupPushAndActivitiesStatesWhenNoSessionExists;
- (_Bool)setOnDiskAccountID:(id)arg1;
- (id)onDiskAccountID;
- (id)accountIDPath;
- (id)init;

@end

