//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudDocsDaemon/BRCLocalItem.h>

@class BRCAliasItem, BRCDesiredVersion, BRCDirectoryItem, BRCItemID, BRCLocalVersion, NSDictionary, NSError, NSMutableSet, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface BRCDocumentItem : BRCLocalItem
{
    BRCLocalVersion *_currentVersion;
    BRCDesiredVersion *_desiredVersion;
    NSMutableSet *_liveConflictLoserEtags;
    NSMutableSet *_resolvedConflictLoserEtags;
}

+ (_Bool)supportsSecureCoding;
+ (struct PQLResultSet *)reverseAliasEnumeratorWithRelativePath:(id)arg1;
+ (struct PQLResultSet *)reverseAliasEnumeratorWithUnsaltedBookmarkData:(id)arg1 session:(id)arg2;
+ (_Bool)parseBookmarkData:(id)arg1 inAccountSession:(id)arg2 docID:(id *)arg3 itemID:(id *)arg4 mangledID:(id *)arg5 unsaltedBookmarkData:(id *)arg6 error:(id *)arg7;
+ (id)unsaltedBookmarkDataWithRelativePath:(id)arg1;
+ (id)bookmarkDataWithRelativePath:(id)arg1;
+ (id)itemResolutionStringWithRelativePath:(id)arg1;
+ (id)bookmarkDataWithItemResolutionString:(id)arg1 serverZone:(id)arg2;
+ (id)unsaltedBookmarkDataWithItemResolutionString:(id)arg1 serverZone:(id)arg2;
@property(readonly, nonatomic) NSSet *resolvedConflictLoserEtags; // @synthesize resolvedConflictLoserEtags=_resolvedConflictLoserEtags;
@property(retain, nonatomic) NSSet *liveConflictLoserEtags; // @synthesize liveConflictLoserEtags=_liveConflictLoserEtags;
@property(readonly, nonatomic) BRCDesiredVersion *desiredVersion; // @synthesize desiredVersion=_desiredVersion;
@property(readonly, nonatomic) BRCLocalVersion *currentVersion; // @synthesize currentVersion=_currentVersion;
- (void).cxx_destruct;
- (void)startDownloadWithOptions:(unsigned long long)arg1 group:(id)arg2;
- (_Bool)evictWithGroup:(id)arg1 error:(id *)arg2;
- (_Bool)_deleteFromDB:(id)arg1 diffs:(unsigned long long)arg2 keepAliases:(_Bool)arg3;
- (_Bool)_updateInDB:(id)arg1 diffs:(unsigned long long)arg2;
- (_Bool)_insertInDB:(id)arg1 dbRowID:(unsigned long long)arg2;
- (_Bool)_nukeVersionsFromDB:(id)arg1;
- (void)_updateReadThrottleIfNeededForRowID:(unsigned long long)arg1 forCreation:(_Bool)arg2;
- (void)_updateUploadThrottleIfNeededWithDiffs:(unsigned long long)arg1;
- (void)_updateLiveConflictLoserFromFSAtPath:(id)arg1;
- (void)addResolvedConflictLoserEtag:(id)arg1;
- (void)removeLiveConflictLoserEtag:(id)arg1;
@property(readonly, nonatomic) NSDictionary *conflictLoserState;
- (void)markOverQuotaWithError:(id)arg1;
- (void)markNeedsUploadOrSyncingUpWithAliasTarget:(id)arg1;
- (void)markUploadedWithRecord:(id)arg1;
- (void)markForceNeedsSyncUp;
- (void)markForceUpload;
- (void)handleUnknownItemError;
- (void)markLatestRequestAcknowledged;
- (void)markLatestSyncRequestRejected;
- (void)markNeedsReading;
- (void)markDead;
- (void)markLiveFromStage;
- (void)clearFromStage;
- (void)appDidResolveConflictLoserWithEtag:(id)arg1;
- (void)forceVersionConflictByClearkingCKInfo;
- (void)forceiWorkConflictEtag:(id)arg1;
- (_Bool)changedAtRelativePath:(id)arg1 scanPackage:(_Bool)arg2;
- (_Bool)updateLocationAndMetaFromFSAtPath:(id)arg1 parentID:(id)arg2;
- (_Bool)updateFromFSAtPath:(id)arg1 parentID:(id)arg2;
- (void)learnItemID:(id)arg1 ownerKey:(id)arg2 path:(id)arg3 markLost:(_Bool)arg4;
- (void)refreshLosersListIfNeededAtPath:(id)arg1;
- (void)updateVersionMetadataFromServerItem:(id)arg1 preventVersionDiffs:(_Bool)arg2;
- (void)updateContentsCKInfoAndDeviceIDFromServerItem:(id)arg1;
- (void)clearDesiredVersion;
- (int)setVersionToStage:(id)arg1 diffsWithServerItem:(unsigned long long)arg2 options:(unsigned int)arg3 needsSave:(_Bool *)arg4;
- (void)stageFaultForCreation:(_Bool)arg1 serverItem:(id)arg2;
- (void)clearVersionSignatures:(unsigned long long)arg1 isPackage:(_Bool)arg2;
- (void)learnThumbnailSignatureFromVersion:(id)arg1;
- (_Bool)validateLoggingToFile:(struct __sFILE *)arg1;
- (unsigned long long)diffAgainstLocalItem:(id)arg1;
- (unsigned long long)diffAgainstServerItem:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_initFromPQLResultSet:(id)arg1 container:(id)arg2 error:(id *)arg3;
- (_Bool)updateXattrInfoFromPathPath:(id)arg1 error:(id *)arg2;
- (id)_initWithRelativePath:(id)arg1 parentID:(id)arg2;
- (id)_initWithLocalItem:(id)arg1;
- (id)_initWithServerItem:(id)arg1 dbRowID:(unsigned long long)arg2;
- (id)descriptionWithContext:(id)arg1;
- (id)setOfContainersIDsWithReverseAliases;
- (struct PQLResultSet *)reverseAliasEnumerator;
- (_Bool)_isInterestingUpdateForNotifs;
@property(readonly, nonatomic) _Bool isInTransfer;
@property(readonly, nonatomic) unsigned int downloadStatus;
@property(readonly, nonatomic) unsigned int queryItemStatus;
@property(readonly, nonatomic) _Bool isDownloadRequested;
@property(readonly, nonatomic) _Bool shouldTransferThumbnail;
@property(readonly, nonatomic) _Bool shouldHaveThumbnail;
- (_Bool)_isSmallAndMostRecentClientsGenerateThumbnails;
@property(readonly, nonatomic) _Bool shouldBeGreedy;
- (_Bool)isSharedByMeWithAShareID;
- (_Bool)isSharedByMe;
@property(readonly, nonatomic) _Bool isVisibleIniCloudDrive;
@property(readonly, nonatomic) _Bool isAutomaticallyEvictable;
@property(readonly, nonatomic) _Bool isEvictable;
@property(readonly, nonatomic) _Bool hasLocalContent;
@property(readonly, nonatomic) BRCDocumentItem *asDocument;
- (_Bool)isFault;
- (_Bool)isDocument;
- (_Bool)isPackage;
@property(readonly, nonatomic) NSString *UTI;
@property(readonly, nonatomic) NSError *uploadError;
@property(readonly, nonatomic) BRCItemID *aliasItemID;
- (id)contentsRecordID;
- (float)prepareEditSyncUpWithOperation:(id)arg1 defaults:(id)arg2;
- (float)prepareDeletionSyncUpWithOperation:(id)arg1 defaults:(id)arg2;
@property(readonly, nonatomic) NSString *bookmarkData;
@property(readonly, nonatomic) NSString *unsaltedBookmarkData;
- (id)itemResolutionString;

// Remaining properties
@property(readonly, nonatomic) BRCAliasItem *asAlias; // @dynamic asAlias;
@property(readonly, nonatomic) BRCDirectoryItem *asDirectory; // @dynamic asDirectory;

@end

