//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudDocsDaemon/BRCSharingModifyShareOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BRCSharingCopyiWorkShareURLOperation : BRCSharingModifyShareOperation
{
    NSString *_appName;
}

- (void).cxx_destruct;
- (void)main;
- (unsigned long long)startActivity;
- (id)initWithShare:(id)arg1 zone:(id)arg2 appName:(id)arg3;
- (_Bool)shouldRetryForError:(id)arg1;

@end

