//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CloudDocsDaemon/BRCContainer-Protocol.h>

@class BRCAccountSession, BRCLocalContainer, BRCServerChangeState, BRCSyncContext, CKRecordZoneID, NSMutableDictionary, NSNumber, NSString, PQLConnection;

@interface BRCServerZone : NSObject <BRCContainer>
{
    BRCServerChangeState *_changeState;
    BRCAccountSession *_session;
    PQLConnection *_db;
    NSString *_zoneName;
    NSNumber *_dbRowID;
    BRCLocalContainer *_localContainer;
    BRCSyncContext *_syncContext;
    _Bool _needsSave;
    NSString *_containerMetadataEtag;
}

@property(nonatomic) _Bool needsSave; // @synthesize needsSave=_needsSave;
@property(readonly, nonatomic) PQLConnection *db; // @synthesize db=_db;
@property(retain, nonatomic) BRCAccountSession *session; // @synthesize session=_session;
@property(nonatomic) BRCLocalContainer *localContainer; // @synthesize localContainer=_localContainer;
@property(readonly, nonatomic) NSString *containerMetadataEtag; // @synthesize containerMetadataEtag=_containerMetadataEtag;
@property(readonly) BRCServerChangeState *changeState; // @synthesize changeState=_changeState;
@property(readonly, nonatomic) NSString *zoneName; // @synthesize zoneName=_zoneName;
@property(retain, nonatomic) NSNumber *dbRowID; // @synthesize dbRowID=_dbRowID;
- (void).cxx_destruct;
- (_Bool)validateItemsLoggingToFile:(struct __sFILE *)arg1 db:(id)arg2;
- (_Bool)validateStructureLoggingToFile:(struct __sFILE *)arg1 db:(id)arg2;
- (_Bool)dumpTablesToContext:(id)arg1 error:(id *)arg2;
- (_Bool)dumpStatusToContext:(id)arg1 error:(id *)arg2;
- (struct PQLResultSet *)itemsEnumeratorWithDB:(id)arg1;
- (id)itemByItemID:(id)arg1;
- (id)deleteAllContentsOperation;
- (void)deleteAllContentsOnServerWithCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)resetServerTruth;
- (void)collectTombstoneRanks:(id)arg1;
- (void)_collectTombstoneForRank:(unsigned long long)arg1;
- (unsigned long long)didSyncDownRequestID:(unsigned long long)arg1 serverChangeToken:(id)arg2 editedRecords:(id)arg3 deletedRecordIDs:(id)arg4 syncStatus:(long long)arg5;
- (void)handleBrokenStructure;
- (_Bool)allocateRanks;
- (struct PQLResultSet *)_enumeratePendingFetchDeletedRecordIDs;
- (struct PQLResultSet *)pendingFetchRecordsEnumerator;
- (_Bool)_saveEditedContentRecords:(id)arg1 syncStatus:(long long)arg2;
- (_Bool)_saveEditedStructureRecords:(id)arg1 deletedRecordIDs:(id)arg2 syncStatus:(long long)arg3;
- (_Bool)_markItemIDDead:(id)arg1 recordID:(id)arg2;
- (_Bool)_saveEditedRecord:(id)arg1 syncStatus:(long long)arg2;
- (_Bool)_saveEditedAliasRecord:(id)arg1;
- (_Bool)_saveEditedDocumentContentRecord:(id)arg1;
- (_Bool)_saveEditedDirOrDocStructureRecord:(id)arg1;
- (_Bool)_saveItemID:(id)arg1 stat:(id)arg2 record:(id)arg3;
- (_Bool)_saveItemID:(id)arg1 stat:(id)arg2 record:(id)arg3 origName:(id)arg4 base:(id)arg5 no:(id)arg6 ext:(id)arg7;
- (id)xattrForSignature:(id)arg1;
- (_Bool)storeXattr:(id)arg1;
- (_Bool)hasXattrWithSignature:(id)arg1;
- (id)initWithZoneName:(id)arg1 dbRowID:(id)arg2 plist:(id)arg3 session:(id)arg4;
@property(readonly, nonatomic) NSMutableDictionary *plist;
- (id)description;
- (id)descriptionWithContext:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
@property(readonly, nonatomic) CKRecordZoneID *zoneID;
@property(readonly, nonatomic) NSString *ownerName;
@property(readonly, nonatomic) BRCSyncContext *syncContext;
- (id)asSharedZone;
- (id)asPrivateZone;
@property(readonly, nonatomic) _Bool isPrivateContainer;
@property(readonly, nonatomic) _Bool isSharedContainer;
@property(readonly, nonatomic) _Bool isSyncingDownForTheFirstTime;

@end

