//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BRCAccountSession, BRCThrottleBase, BRCTransferStream, BRCUserDefaults, CKContainer, NSString;

__attribute__((visibility("hidden")))
@interface BRCSyncContext : NSObject
{
    CKContainer *_ckContainer;
    NSString *_contextIdentifier;
    _Bool _isShared;
    _Bool _isCancelled;
    BRCAccountSession *_session;
    BRCThrottleBase *_readerThrottle;
    BRCThrottleBase *_applyThrottle;
    BRCThrottleBase *_downloadThrottle;
    BRCThrottleBase *_uploadThrottle;
    BRCTransferStream *_uploadStream;
    BRCTransferStream *_downloadStream;
}

+ (id)contextIdentifierForZone:(id)arg1;
@property(readonly, nonatomic) _Bool isShared; // @synthesize isShared=_isShared;
@property(readonly, nonatomic) BRCTransferStream *downloadStream; // @synthesize downloadStream=_downloadStream;
@property(readonly, nonatomic) BRCTransferStream *uploadStream; // @synthesize uploadStream=_uploadStream;
@property(readonly, nonatomic) BRCThrottleBase *uploadThrottle; // @synthesize uploadThrottle=_uploadThrottle;
@property(readonly, nonatomic) BRCThrottleBase *downloadThrottle; // @synthesize downloadThrottle=_downloadThrottle;
@property(readonly, nonatomic) BRCThrottleBase *applyThrottle; // @synthesize applyThrottle=_applyThrottle;
@property(readonly, nonatomic) BRCThrottleBase *readerThrottle; // @synthesize readerThrottle=_readerThrottle;
@property(readonly, nonatomic) NSString *contextIdentifier; // @synthesize contextIdentifier=_contextIdentifier;
@property(readonly, nonatomic) BRCAccountSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)close;
- (void)waitForAllOperations;
- (void)cancel;
- (void)resume;
- (void)addOperation:(id)arg1 allowsCellularAccess:(id)arg2;
- (void)addOperation:(id)arg1;
- (_Bool)allowsCellularAccess;
- (void)notifyDuetFromAccessByBundleID:(id)arg1;
- (id)_database;
@property(readonly, nonatomic) CKContainer *ckContainer;
- (void)setupIfNeeded;
- (id)initWithZone:(id)arg1;
- (id)initWithSession:(id)arg1 contextIdentifier:(id)arg2 isShared:(_Bool)arg3;
- (id)description;
@property(readonly, nonatomic) BRCUserDefaults *defaults;

@end

