//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameController/GCController.h>

#import <GameController/NSSecureCoding-Protocol.h>

@class NSMutableArray, NSObject, NSString;
@protocol GCNamedProfile, OS_dispatch_queue;

@interface _GCController : GCController <NSSecureCoding>
{
    CDUnknownBlockType _controllerPausedHandler;
    NSString *_vendorName;
    long long _playerIndex;
    id <GCNamedProfile> _profile;
    struct __IOHIDDevice *_deviceRef;
    NSMutableArray *_allDeviceRefs;
    char *_deviceHIDReportBuffer;
    unsigned int _service;
    unsigned long long _deviceHash;
    NSObject<OS_dispatch_queue> *_handlerQueue;
}

+ (_Bool)supportsSecureCoding;
- (unsigned int)service;
- (id)deviceRefs;
- (struct __IOHIDDevice *)deviceRef;
- (void)setProfile:(id)arg1;
- (id)profile;
- (void)setControllerPausedHandler:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)controllerPausedHandler;
- (void).cxx_destruct;
- (id)motion;
- (id)extendedGamepad;
- (id)gamepad;
- (id)description;
- (void)setPlayerIndex:(long long)arg1;
- (long long)playerIndex;
- (_Bool)isAttachedToDevice;
- (id)vendorName;
- (id)handlerQueue;
- (void)setHandlerQueue:(id)arg1;
- (void)clearDeviceRef;
- (id)initWithDeviceRef:(struct __IOHIDDevice *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setHidReportBuffer:(char *)arg1;
- (char *)hidReportBuffer;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithProfile:(id)arg1;
- (unsigned long long)deviceHash;
- (void)removeDeviceRef:(struct __IOHIDDevice *)arg1;
- (void)addDeviceRefs:(id)arg1;
- (_Bool)isEqualToController:(id)arg1;

@end

