//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CAMCaptureConversions : NSObject
{
}

+ (long long)viewContentModeForPreviewViewAspectMode:(long long)arg1;
+ (id)previewLayerVideoGravityForPreviewViewAspectMode:(long long)arg1;
+ (long long)whiteBalanceModeForCaptureWhiteBalanceMode:(long long)arg1;
+ (long long)captureWhiteBalanceModeForWhiteBalanceMode:(long long)arg1;
+ (long long)exposureModeForCaptureExposureMode:(long long)arg1;
+ (long long)captureExposureModeForExposureMode:(long long)arg1;
+ (long long)focusModeForCaptureFocusMode:(long long)arg1;
+ (long long)captureFocusModeForFocusMode:(long long)arg1;
+ (long long)irisModeForCaptureIrisMode:(long long)arg1;
+ (long long)captureIrisModeForIrisMode:(long long)arg1;
+ (long long)hdrModeForCaptureHDRMode:(long long)arg1;
+ (long long)captureHDRModeForHDRMode:(long long)arg1;
+ (long long)torchModeForCaptureTorchMode:(long long)arg1;
+ (long long)captureTorchModeForTorchMode:(long long)arg1;
+ (long long)flashModeForCaptureFlashMode:(long long)arg1;
+ (long long)captureFlashModeForFlashMode:(long long)arg1;

@end

