//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface CAMFramerateIndicatorView : UIView
{
    long long _style;
    UIImageView *__borderImageView;
    UILabel *__topLabel;
    UILabel *__bottomLabel;
}

@property(readonly, nonatomic) UILabel *_bottomLabel; // @synthesize _bottomLabel=__bottomLabel;
@property(readonly, nonatomic) UILabel *_topLabel; // @synthesize _topLabel=__topLabel;
@property(readonly, nonatomic) UIImageView *_borderImageView; // @synthesize _borderImageView=__borderImageView;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_updateLabels;
- (id)_labelText;
- (long long)_framesPerSecond;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonCAMFramerateIndicatorViewInitialization;

@end

