//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CameraUI/CAMCaptureCommand.h>

#import <CameraUI/NSCoding-Protocol.h>
#import <CameraUI/NSCopying-Protocol.h>

@interface CAMHDRCommand : CAMCaptureCommand <NSCopying, NSCoding>
{
    _Bool __shouldCaptureEV0;
    long long __HDRMode;
}

@property(readonly, nonatomic) _Bool _shouldCaptureEV0; // @synthesize _shouldCaptureEV0=__shouldCaptureEV0;
@property(readonly, nonatomic) long long _HDRMode; // @synthesize _HDRMode=__HDRMode;
- (void)executeWithContext:(id)arg1;
- (long long)_captureHDRModeForHDRMode:(long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithHDRMode:(long long)arg1 shouldCaptureEV0:(_Bool)arg2;
- (id)initWithHDRMode:(long long)arg1;

@end

