//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSCache;
@protocol OS_dispatch_queue;

@interface FBSqliteDatabaseConnection : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    struct sqlite3 *_queue_dbConnection;
    NSCache *_queue_queryCache;
}

+ (int)_sqliteOpenFlagsForDataProtectionClass:(unsigned long long)arg1;
- (id)lastErrorMessage;
- (void)performSyncWithDatabase:(CDUnknownBlockType)arg1;
- (void)performWithDatabase:(CDUnknownBlockType)arg1;
- (id)prepareStatement:(id)arg1;
- (void)dealloc;
- (id)_initWithSqlitePath:(id)arg1 dataProtectionClass:(unsigned long long)arg2;
- (id)initWithInMemoryDatabase;
- (id)initWithURL:(id)arg1 dataProtectionClass:(unsigned long long)arg2;
- (id)initWithURL:(id)arg1;

@end

