//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreHAP/HAPAccessoryServer.h>

#import <CoreHAP/HAPFragmentationStreamDelegate-Protocol.h>
#import <CoreHAP/HAPSecuritySessionDelegate-Protocol.h>
#import <CoreHAP/HAPStreamDelegate-Protocol.h>
#import <CoreHAP/HAPTimerDelegate-Protocol.h>

@class HAPExponentialBackoffTimer, HAPFragmentationStream, HAPRelayStream, HAPSecuritySession, NSMapTable, NSMutableArray, NSOperationQueue, NSString;

@interface HAPAccessoryServerRelay : HAPAccessoryServer <HAPSecuritySessionDelegate, HAPFragmentationStreamDelegate, HAPTimerDelegate, HAPStreamDelegate>
{
    _Bool _securitySessionOpen;
    _Bool _securitySessionOpening;
    _Bool _discovered;
    _Bool _shouldDiscover;
    unsigned short _nextRequestTransactionIdentifier;
    HAPRelayStream *_stream;
    NSMutableArray *_pendingRequests;
    NSMapTable *_pendingResponses;
    NSOperationQueue *_requestOperationQueue;
    HAPFragmentationStream *_fragmentationStream;
    HAPSecuritySession *_securitySession;
    NSOperationQueue *_pairVerifyOperationQueue;
    HAPExponentialBackoffTimer *_reachabilityProbeTimer;
    unsigned long long _configurationNumber;
}

@property(nonatomic) _Bool shouldDiscover; // @synthesize shouldDiscover=_shouldDiscover;
@property(nonatomic, getter=hasDiscovered) _Bool discovered; // @synthesize discovered=_discovered;
@property(nonatomic) unsigned long long configurationNumber; // @synthesize configurationNumber=_configurationNumber;
@property(retain, nonatomic) HAPExponentialBackoffTimer *reachabilityProbeTimer; // @synthesize reachabilityProbeTimer=_reachabilityProbeTimer;
@property(readonly, nonatomic) NSOperationQueue *pairVerifyOperationQueue; // @synthesize pairVerifyOperationQueue=_pairVerifyOperationQueue;
@property(nonatomic, getter=isSecuritySessionOpening) _Bool securitySessionOpening; // @synthesize securitySessionOpening=_securitySessionOpening;
@property(nonatomic, getter=isSecuritySessionOpen) _Bool securitySessionOpen; // @synthesize securitySessionOpen=_securitySessionOpen;
@property(retain, nonatomic) HAPSecuritySession *securitySession; // @synthesize securitySession=_securitySession;
@property(readonly, nonatomic) unsigned short nextRequestTransactionIdentifier; // @synthesize nextRequestTransactionIdentifier=_nextRequestTransactionIdentifier;
@property(readonly, nonatomic) HAPFragmentationStream *fragmentationStream; // @synthesize fragmentationStream=_fragmentationStream;
@property(readonly, nonatomic) NSOperationQueue *requestOperationQueue; // @synthesize requestOperationQueue=_requestOperationQueue;
@property(readonly, nonatomic) NSMapTable *pendingResponses; // @synthesize pendingResponses=_pendingResponses;
@property(readonly, nonatomic) NSMutableArray *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
@property(readonly, nonatomic) HAPRelayStream *stream; // @synthesize stream=_stream;
- (void).cxx_destruct;
- (void)timerDidFire:(id)arg1;
- (void)fragmentationStream:(id)arg1 didReceiveData:(id)arg2 transactionIdentifier:(unsigned short)arg3 error:(id)arg4;
- (void)fragmentationStream:(id)arg1 didCloseWithError:(id)arg2;
- (void)securitySession:(id)arg1 didCloseWithError:(id)arg2;
- (void)securitySessionDidOpen:(id)arg1;
- (void)securitySessionIsOpening:(id)arg1;
- (void)securitySession:(id)arg1 didReceiveSetupExchangeData:(id)arg2;
- (id)securitySession:(id)arg1 didReceiveRequestForPeerPairingIdentityWithIdentifier:(id)arg2 error:(id *)arg3;
- (id)securitySession:(id)arg1 didReceiveLocalPairingIdentityRequestWithError:(id *)arg2;
- (void)stream:(id)arg1 didReceiveData:(id)arg2 withIdentifier:(id)arg3;
- (void)stream:(id)arg1 didFailToWriteDataWithIdentifier:(id)arg2 error:(id)arg3;
- (void)stream:(id)arg1 didCloseWithError:(id)arg2;
- (void)streamDidResume:(id)arg1;
- (void)streamDidSuspend:(id)arg1;
- (id)_decryptData:(id)arg1 error:(id *)arg2;
- (id)_encryptData:(id)arg1 error:(id *)arg2;
- (void)_handleSecuritySessionSetupExchangeData:(id)arg1;
- (void)_establishSecuritySession;
- (void)_cancelAllQueuedOperationsWithError:(id)arg1;
- (void)_resumeAllOperations;
- (void)_suspendAllOperations;
- (void)_enqueueRequest:(id)arg1;
- (void)_handleFragmentedResponse:(id)arg1 transactionIdentifier:(unsigned short)arg2 error:(id)arg3;
- (void)_handleReceivedMessageData:(id)arg1 withIdentifier:(id)arg2 error:(id)arg3;
- (void)_sendRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (unsigned short)_nextTransactionIdentifier;
- (id)getLocalPairingIdentityAndAllowCreation:(_Bool)arg1 error:(id *)arg2;
- (void)listPairingsWithCompletionQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)removePairingForCurrentControllerOnQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)removePairingWithIdentifier:(id)arg1 publicKey:(id)arg2 queue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)addPairingWithIdentifier:(id)arg1 publicKey:(id)arg2 admin:(_Bool)arg3 queue:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (_Bool)tryPairingPassword:(id)arg1 error:(id *)arg2;
- (_Bool)stopPairingWithError:(id *)arg1;
- (void)continuePairingAfterAuthPrompt;
- (void)startPairing;
- (void)_handleNotificationResponse:(id)arg1;
- (void)enableEvents:(_Bool)arg1 forCharacteristics:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3 queue:(id)arg4;
- (void)_handleCharacteristicWriteResponse:(id)arg1 characteristicWriteRequestTuples:(id)arg2 error:(id)arg3 completionQueue:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)writeCharacteristicValues:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)writeValue:(id)arg1 forCharacteristic:(id)arg2 authorizationData:(id)arg3 queue:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)_handleCharacteristicReadResponse:(id)arg1 characteristics:(id)arg2 error:(id)arg3 completionQueue:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)readCharacteristicValues:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)readValueForCharacteristic:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_parseAttributeDatabase:(id)arg1 configurationNumber:(id)arg2;
- (void)discoverAccessories;
- (void)_handleReachabilityProbeFire;
- (void)_endReachabilityProbe;
- (void)_startReachabilityProbe;
- (void)identifyWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)isPaired;
- (_Bool)hasPairings;
- (long long)linkType;
- (void)dealloc;
- (id)initWithStream:(id)arg1 name:(id)arg2 identifier:(id)arg3 keyStore:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

