//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface SearchUIContentAdvisoryView : UIView
{
    NSString *_advisoryString;
}

@property(retain) NSString *advisoryString; // @synthesize advisoryString=_advisoryString;
- (void).cxx_destruct;
- (id)initWithString:(id)arg1 style:(unsigned long long)arg2 large:(_Bool)arg3;

@end

