//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SearchUIVerticalResultView;

@interface SearchUICollectionViewCell : UICollectionViewCell
{
    SearchUIVerticalResultView *_resultView;
}

@property(retain, nonatomic) SearchUIVerticalResultView *resultView; // @synthesize resultView=_resultView;
- (void).cxx_destruct;
- (void)updateWithResultView:(id)arg1;

@end

