//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import <SearchUI/UINavigationControllerDelegate-Protocol.h>

@class NSString;

@interface SearchUITestNavigationController : UINavigationController <UINavigationControllerDelegate>
{
}

- (id)tableViewController;
- (void)showTableView;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)selectRowAtIndexPath:(id)arg1;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (id)initWithResults:(id)arg1 style:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

