//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface SBUIKeyboardEnablementManager : NSObject
{
    NSHashTable *_disabledContexts;
    _Bool _disabled;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)description;
- (void)enableAutomaticAppearanceForContext:(id)arg1;
- (void)disableAutomaticAppearanceForContext:(id)arg1;
- (id)init;

@end

