//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayerUI/JSExport-Protocol.h>

@class JSValue, NSString;

@protocol MPUExtrasJSITunesStore <JSExport>
- (void)loadStoreURL:(NSString *)arg1 playOnLaunch:(JSValue *)arg2;

@optional
- (void)loadStoreURL:(NSString *)arg1 playOnLaunch:(JSValue *)arg2 __JS_EXPORT_AS__loadStoreURL:(id)arg3;
@end

