//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Notes/ICIndexItemsOperation.h>

@interface ICReindexAllItemsOperation : ICIndexItemsOperation
{
}

- (void)main;
- (id)searchableItemIdentifiersToDeleteFromDataSource:(id)arg1;
- (id)searchableItemsToIndexFromDataSource:(id)arg1;
- (_Bool)shouldDeleteAllItemsBeforeIndexing;

@end

