//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PhotosUI/PUPhotoLibraryUIChangeObserver-Protocol.h>

@class NSArray, NSString, PHManualFetchResult;

__attribute__((visibility("hidden")))
@interface PUAssetHidingHelper : NSObject <PUPhotoLibraryUIChangeObserver>
{
    _Bool _areAllAssetsHidden;
    _Bool _didCheckAllAssetHidden;
    _Bool _canToogleAssetsVisibility;
    _Bool _didCheckCanToogleAssetsVisibility;
    PHManualFetchResult *__assetsFetchResults;
}

@property(retain, nonatomic, setter=_setAssetsFetchResult:) PHManualFetchResult *_assetsFetchResults; // @synthesize _assetsFetchResults=__assetsFetchResults;
- (void).cxx_destruct;
- (void)photoLibraryDidChangeOnMainQueue:(id)arg1;
- (void)prepareForPhotoLibraryChange:(id)arg1;
- (id)attemptTogglingAssetsVisibilityFromViewController:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)alertControllerForTogglingAssetsVisibilityWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)applyHiddenState:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)menuItemTitleForTogglingAssetsVisibility;
- (_Bool)canToggleAssetsVisibility;
@property(readonly, nonatomic) _Bool isHiding;
- (_Bool)_areAllAssetsHidden;
- (void)_prepareAssetsVisibilityValueIfNeeded;
@property(copy, nonatomic) NSArray *assets;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

