//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface PUAvalancheReviewControllerSpec : NSObject
{
}

@property(readonly, nonatomic) double interItemSpacing;
- (_Bool)allowsInterfaceRotation;
- (struct UIEdgeInsets)collectionViewLayoutContentInsetForOrientation:(long long)arg1;
@property(readonly, nonatomic) unsigned long long selectionBadgeCorner;
@property(readonly, nonatomic) struct UIOffset selectionBadgeOffset;
@property(readonly, nonatomic) struct CGSize selectionBadgeSize;

@end

