//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PhotosUI/NSCopying-Protocol.h>

__attribute__((visibility("hidden")))
@interface PUBadgeInfo : NSObject <NSCopying>
{
    long long _style;
    long long _numberOfPhotos;
    CDUnknownBlockType __numberOfPhotosProvider;
}

+ (id)badgeInfoWithBurstStyleNumberOfPhotosProvider:(CDUnknownBlockType)arg1;
+ (id)badgeInfoWithBurstStyleNumberOfPhotos:(long long)arg1;
+ (id)badgeInfoWithPhotoIrisStyle;
+ (id)badgeInfoWithHDRPhotoIrisStyle;
+ (id)badgeInfoWithHDRStyle;
@property(copy, nonatomic, setter=_setNumberOfPhotosProvider:) CDUnknownBlockType _numberOfPhotosProvider; // @synthesize _numberOfPhotosProvider=__numberOfPhotosProvider;
- (void)_setNumberOfPhotos:(long long)arg1;
- (void)_setStyle:(long long)arg1;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
@property(nonatomic) long long numberOfPhotos; // @synthesize numberOfPhotos=_numberOfPhotos;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

