//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class PLManagedAsset, UIImageView;

__attribute__((visibility("hidden")))
@interface PUBlinkRenderingTest : UIViewController
{
    PLManagedAsset *_asset;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) PLManagedAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithManagedAsset:(id)arg1;

@end

