//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PhotosUI/NSCopying-Protocol.h>

@class NSString, PUModelTileTransform;

__attribute__((visibility("hidden")))
@interface PUDisplayTileTransform : NSObject <NSCopying>
{
    _Bool _hasUserInput;
    NSString *_userInputOriginIdentifier;
    double __initialScale;
    struct CGSize _transformPadding;
    struct CGSize __initialSize;
    struct CGSize __displaySize;
    struct CGAffineTransform _affineTransform;
}

+ (id)displayTileTransformWithModelTileTransform:(id)arg1 initialScale:(double)arg2 initialSize:(struct CGSize)arg3 displaySize:(struct CGSize)arg4 secondaryDisplayTileTransform:(id)arg5;
@property(nonatomic, setter=_setDisplaySize:) struct CGSize _displaySize; // @synthesize _displaySize=__displaySize;
@property(nonatomic, setter=_setInitialSize:) struct CGSize _initialSize; // @synthesize _initialSize=__initialSize;
@property(nonatomic, setter=_setInitialScale:) double _initialScale; // @synthesize _initialScale=__initialScale;
- (void)_setTransformPadding:(struct CGSize)arg1;
@property(nonatomic) struct CGSize transformPadding; // @synthesize transformPadding=_transformPadding;
- (void)_setUserInputOriginIdentifier:(id)arg1;
@property(copy, nonatomic) NSString *userInputOriginIdentifier; // @synthesize userInputOriginIdentifier=_userInputOriginIdentifier;
- (void)_setHasUserInput:(_Bool)arg1;
@property(nonatomic) _Bool hasUserInput; // @synthesize hasUserInput=_hasUserInput;
- (void)_setAffineTransform:(struct CGAffineTransform)arg1;
@property(nonatomic) struct CGAffineTransform affineTransform; // @synthesize affineTransform=_affineTransform;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)newDisplayTileTransformWithUserAffineTransform:(struct CGAffineTransform)arg1 userInputOriginIdentifier:(id)arg2;
@property(readonly, nonatomic) PUModelTileTransform *modelTileTransform;

@end

