//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayoutInvalidationContext.h>

__attribute__((visibility("hidden")))
@interface PUHorizontalTiledCollectionViewLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext
{
    _Bool _invalidateCachedLayout;
}

- (void)_setInvalidateCachedLayout:(_Bool)arg1;
@property(nonatomic) _Bool invalidateCachedLayout; // @synthesize invalidateCachedLayout=_invalidateCachedLayout;

@end

