//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUResultRecord.h>

@class NSPredicate, NSSet, PHFetchResult;

__attribute__((visibility("hidden")))
@interface PUMutableResultRecord : PUResultRecord
{
    PHFetchResult *_filteredFetchResult;
    NSPredicate *_inclusionPredicate;
    _Bool _filteredFetchResultIsValid;
    _Bool _inclusionPredicateIsValid;
    _Bool _reverseSortOrder;
    NSSet *_excludedOids;
    NSSet *_includedOids;
    PHFetchResult *_fetchResult;
}

@property(readonly, nonatomic) _Bool reverseSortOrder; // @synthesize reverseSortOrder=_reverseSortOrder;
@property(readonly, nonatomic) PHFetchResult *fetchResult; // @synthesize fetchResult=_fetchResult;
@property(readonly, nonatomic) NSSet *includedOids; // @synthesize includedOids=_includedOids;
@property(readonly, nonatomic) NSSet *excludedOids; // @synthesize excludedOids=_excludedOids;
- (void).cxx_destruct;
- (void)_updateFilteredFetchResultIfNeeded;
- (void)_invalidateFilteredFetchResult;
@property(readonly, nonatomic) PHFetchResult *filteredFetchResult;
@property(readonly, nonatomic) PHFetchResult *exposedFetchResult;
- (void)setReverseSortOrder:(_Bool)arg1;
- (void)setFetchResult:(id)arg1;
- (void)setFetchResult:(id)arg1 reverseSortOrder:(_Bool)arg2;
- (void)stopExcludingOids:(id)arg1;
- (void)excludeOids:(id)arg1;
@property(readonly, nonatomic) NSPredicate *inclusionPredicate;
- (void)_invalidateInclusionPredicate;
- (void)_setIncludeOids:(id)arg1;
- (void)stopIncludingAllOids;
- (void)includeOids:(id)arg1;
- (void)invalidateFetchResultAssetCache;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

