//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUTilingLayoutInvalidationContext.h>

@interface PUOneUpTilingLayoutInvalidationContext : PUTilingLayoutInvalidationContext
{
    _Bool _invalidatedContentGuideInsets;
    _Bool _invalidatedCommentsTile;
    _Bool _invalidatedVideoPlaceholderTile;
}

@property(nonatomic) _Bool invalidatedVideoPlaceholderTile; // @synthesize invalidatedVideoPlaceholderTile=_invalidatedVideoPlaceholderTile;
@property(nonatomic) _Bool invalidatedCommentsTile; // @synthesize invalidatedCommentsTile=_invalidatedCommentsTile;
@property(nonatomic) _Bool invalidatedContentGuideInsets; // @synthesize invalidatedContentGuideInsets=_invalidatedContentGuideInsets;
- (void)_setInvalidatedVideoPlaceholderTile:(_Bool)arg1;
- (void)_setInvalidatedCommentsTile:(_Bool)arg1;
- (void)_setInvalidatedContentGuideInsets:(_Bool)arg1;

@end

