//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUPhotoBrowserControllerSpec.h>

@interface PUPhotoBrowserControllerPadSpec : PUPhotoBrowserControllerSpec
{
}

- (id)avalancheReviewControllerSpec;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldShowPhotoScrubber;
- (_Bool)shouldShowToolbarItemsInNavigationBar;
- (id)newPhotoBrowserControllerForPhotoAtIndexPath:(id)arg1 assetCollections:(id)arg2 dataSource:(id)arg3;

@end

