//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface PUPlaceholderView : UIView
{
    unsigned long long _type;
    UIView *__container;
    UIImageView *__imageView;
    UILabel *__airPlayLabel;
    UILabel *__appleTVMessageLabel;
}

@property(retain, nonatomic, setter=_setAppleTVMessageLabel:) UILabel *_appleTVMessageLabel; // @synthesize _appleTVMessageLabel=__appleTVMessageLabel;
@property(retain, nonatomic, setter=_setAirPlayLabel:) UILabel *_airPlayLabel; // @synthesize _airPlayLabel=__airPlayLabel;
@property(retain, nonatomic, setter=_setImageView:) UIImageView *_imageView; // @synthesize _imageView=__imageView;
@property(retain, nonatomic, setter=_setContainer:) UIView *_container; // @synthesize _container=__container;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)_appleTVMessage;
- (void)_setup;
- (id)initWithType:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

