//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUViewControllerSpecChange.h>

__attribute__((visibility("hidden")))
@interface PUSlideshowViewControllerSpecChange : PUViewControllerSpecChange
{
    _Bool _chromeVisibilityChanged;
    _Bool _shouldShowPlaceholderChanged;
    _Bool _shouldShowChromeBarsChanged;
    _Bool _shouldObserveAirplayRouteChanged;
    _Bool _shouldShowAirplayButtonChanged;
}

- (void)_setShouldShowAirplayButtonChanged:(_Bool)arg1;
@property(nonatomic) _Bool shouldShowAirplayButtonChanged; // @synthesize shouldShowAirplayButtonChanged=_shouldShowAirplayButtonChanged;
- (void)_setShouldObserveAirplayRouteChanged:(_Bool)arg1;
@property(nonatomic) _Bool shouldObserveAirplayRouteChanged; // @synthesize shouldObserveAirplayRouteChanged=_shouldObserveAirplayRouteChanged;
- (void)_setShouldShowChromeBarsChanged:(_Bool)arg1;
@property(nonatomic) _Bool shouldShowChromeBarsChanged; // @synthesize shouldShowChromeBarsChanged=_shouldShowChromeBarsChanged;
- (void)_setShouldShowPlaceholderChanged:(_Bool)arg1;
@property(nonatomic) _Bool shouldShowPlaceholderChanged; // @synthesize shouldShowPlaceholderChanged=_shouldShowPlaceholderChanged;
@property(readonly, nonatomic) _Bool chromeVisibilityChanged; // @synthesize chromeVisibilityChanged=_chromeVisibilityChanged;
- (_Bool)changed;

@end

