//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PUAlbumListViewController, PUAlbumListViewControllerSpec, PUFeedViewControllerSpec, PUZoomableGridViewControllerSpec;

@interface PUTabbedLibraryViewControllerSpec : NSObject
{
    PUAlbumListViewControllerSpec *_albumListViewControllerSpec;
    PUAlbumListViewController *_createAlbumListViewController;
    PUAlbumListViewController *_createSharedAlbumListViewController;
    PUZoomableGridViewControllerSpec *_zoomableGridViewControllerSpec;
    PUFeedViewControllerSpec *_feedViewControllerSpec;
}

@property(readonly, nonatomic) PUFeedViewControllerSpec *feedViewControllerSpec; // @synthesize feedViewControllerSpec=_feedViewControllerSpec;
@property(readonly, nonatomic) PUZoomableGridViewControllerSpec *zoomableGridViewControllerSpec; // @synthesize zoomableGridViewControllerSpec=_zoomableGridViewControllerSpec;
@property(readonly, nonatomic) PUAlbumListViewController *createSharedAlbumListViewController; // @synthesize createSharedAlbumListViewController=_createSharedAlbumListViewController;
@property(readonly, nonatomic) PUAlbumListViewController *createAlbumListViewController; // @synthesize createAlbumListViewController=_createAlbumListViewController;
@property(readonly, nonatomic) PUAlbumListViewControllerSpec *albumListViewControllerSpec; // @synthesize albumListViewControllerSpec=_albumListViewControllerSpec;
- (void).cxx_destruct;

@end

