//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUViewModelChange.h>

@interface PUToolbarViewModelChange : PUViewModelChange
{
    _Bool _toolbarItemsChanged;
    _Bool _accessoryViewChanged;
    _Bool _accessoryViewTopOutsetChanged;
    _Bool _maximumHeightChanged;
}

- (void)_setMaximumHeightChanged:(_Bool)arg1;
@property(nonatomic) _Bool maximumHeightChanged; // @synthesize maximumHeightChanged=_maximumHeightChanged;
- (void)_setAccessoryViewTopOutsetChanged:(_Bool)arg1;
@property(nonatomic) _Bool accessoryViewTopOutsetChanged; // @synthesize accessoryViewTopOutsetChanged=_accessoryViewTopOutsetChanged;
- (void)_setAccessoryViewChanged:(_Bool)arg1;
@property(nonatomic) _Bool accessoryViewChanged; // @synthesize accessoryViewChanged=_accessoryViewChanged;
- (void)_setToolbarItemsChanged:(_Bool)arg1;
@property(nonatomic) _Bool toolbarItemsChanged; // @synthesize toolbarItemsChanged=_toolbarItemsChanged;
- (_Bool)hasChanges;

@end

