//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@interface UICollectionView (PhotosUI)
- (id)next:(long long)arg1 indexPathFromIndexPath:(id)arg2;
- (void)pu_scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)pu_scrollToRect:(struct CGRect)arg1 atScrollPosition:(unsigned long long)arg2 animated:(_Bool)arg3;
@end

