//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WatchKit/SPInterfaceObject.h>

@interface SPInterfaceButton : SPInterfaceObject
{
}

- (void)setEnabled:(_Bool)arg1;
- (void)setBackgroundImageNamed:(id)arg1;
- (void)setBackgroundImageData:(id)arg1;
- (void)setBackgroundImage:(id)arg1;
- (void)setAttributedTitle:(id)arg1;
- (void)setTitle:(id)arg1;

@end

