//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class RUIElement, RUIPasscodeView;

@protocol RUIPasscodeViewDelegate
- (void)passcodeViewOM:(RUIPasscodeView *)arg1 activatedElement:(RUIElement *)arg2 completion:(void (^)(_Bool, NSError *))arg3;
@end

