//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameCenterFoundation/GKInternalRepresentation.h>

@class GKPlayerCredential, NSURL;

@interface GKAuthenticateResponse : GKInternalRepresentation
{
    _Bool _loginDisabled;
    _Bool _passwordChangeRequired;
    _Bool _shouldShowLinkAccountsUI;
    GKPlayerCredential *_credential;
    NSURL *_passwordChangeURL;
}

+ (id)secureCodedPropertyKeys;
@property(nonatomic) _Bool shouldShowLinkAccountsUI; // @synthesize shouldShowLinkAccountsUI=_shouldShowLinkAccountsUI;
@property(retain, nonatomic) NSURL *passwordChangeURL; // @synthesize passwordChangeURL=_passwordChangeURL;
@property(nonatomic) _Bool passwordChangeRequired; // @synthesize passwordChangeRequired=_passwordChangeRequired;
@property(nonatomic) _Bool loginDisabled; // @synthesize loginDisabled=_loginDisabled;
@property(retain, nonatomic) GKPlayerCredential *credential; // @synthesize credential=_credential;
- (void)dealloc;

@end

