//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/DevicePINPane.h>

@class CDPPaneHeaderView;

@interface CDPPassphraseEntryPane : DevicePINPane
{
    CDPPaneHeaderView *_headerView;
    double _keyboardOffset;
    _Bool _formPresentation;
}

@property(nonatomic) _Bool formPresentation; // @synthesize formPresentation=_formPresentation;
- (void).cxx_destruct;
- (void)_layoutPinViewWithHeight:(double)arg1;
- (void)_layoutHeaderRect;
- (void)_layoutSubviews;
- (void)layoutSubviews;
- (id)headerView;
- (double)keyboardHeightOffset;
- (void)_keyboardLayoutChanged;
- (_Bool)isSmallScreen;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

