//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreCDPUI/CDPPassphraseEntryViewController.h>

#import <CoreCDPUI/CDPRemoteSecretEntryPaneDelegate-Protocol.h>
#import <CoreCDPUI/DevicePINControllerDelegate-Protocol.h>

@class CDPDevice, CDPRemoteDeviceSecretValidator, NSNumber, NSString;
@protocol CDPRemoteSecretEntryDelegate;

@interface CDPRemoteSecretEntryViewController : CDPPassphraseEntryViewController <DevicePINControllerDelegate, CDPRemoteSecretEntryPaneDelegate>
{
    _Bool _hasNumericSecret;
    NSNumber *_numericSecretLength;
    CDPDevice *_device;
    long long _remainingAttempts;
    CDPRemoteDeviceSecretValidator *_validator;
    unsigned long long _escapeOffer;
    id <CDPRemoteSecretEntryDelegate> _delegate;
    unsigned long long _validationState;
    _Bool _cancelValidationOnBack;
}

@property(nonatomic) _Bool cancelValidationOnBack; // @synthesize cancelValidationOnBack=_cancelValidationOnBack;
@property(readonly, nonatomic) CDPRemoteDeviceSecretValidator *validator; // @synthesize validator=_validator;
- (void).cxx_destruct;
- (void)enableUserInteractionAndStopSpinner;
- (void)disableUserInteractionAndStartSpinner;
- (void)remoteSecretPane:(id)arg1 escapeHatchTappedWithOffer:(unsigned long long)arg2 device:(id)arg3;
- (void)didCancelEnteringPIN;
- (void)didEnterValidRemoteSecret:(id)arg1;
- (void)didAcceptEnteredPIN:(id)arg1;
- (void)showIncorrectRemoteSecretAlertWithIsLocalSecret:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)validatePIN:(id)arg1;
- (_Bool)simplePIN;
- (_Bool)pinIsAcceptable:(id)arg1 outError:(id *)arg2;
- (id)pinInstructionsPrompt;
- (id)title;
- (void)setPane:(id)arg1;
- (_Bool)useProgressiveDelays;
- (id)initWithValidator:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)initWithIsNumeric:(_Bool)arg1 numericLength:(id)arg2 validator:(id)arg3 escapeOffer:(unsigned long long)arg4 delegate:(id)arg5;
- (id)initWithDevice:(id)arg1 validator:(id)arg2 escapeOffer:(unsigned long long)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

