//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertController.h>

@interface UIAlertController (TelephonyUI)
+ (id)networkUnavailableAlertControllerWithCallService:(int)arg1 dialType:(long long)arg2 preferredStyle:(long long)arg3;
+ (id)networkUnavailableAlertControllerWithCallService:(int)arg1 dialType:(long long)arg2;
+ (id)enableWiFiCallingAlertControllerWithPreferredStyle:(long long)arg1;
+ (id)enableWiFiCallingAlertController;
@end

