//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreFoundation/CFPrefsPlistSource.h>

@interface CFPrefsCloudSource : CFPrefsPlistSource
{
    const char *_configPath;
    const char *_storeName;
}

- (void)finalize;
- (void)dealloc;
- (void)setStoreName:(struct __CFString *)arg1;
- (void)setConfigurationPath:(struct __CFString *)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)mergeIntoDictionary:(struct __CFDictionary *)arg1;
- (void)fullCloudSynchronizeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)alreadylocked_updateObservingRemoteChanges;
- (id)createSynchronizeMessage;
- (id)initWithDomain:(struct __CFString *)arg1 user:(struct __CFString *)arg2 byHost:(_Bool)arg3 containerPath:(struct __CFString *)arg4;

@end

