//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImage, UIImageView, _UIBackdropView;

@interface __PGButton : UIButton
{
    _UIBackdropView *_backdropView;
    UIImageView *_highlightImageView;
    UIImage *_backgroundImage;
    UIImageView *_foregroundImageView;
    long long _buttonStyle;
}

@property(readonly, nonatomic) long long buttonStyle; // @synthesize buttonStyle=_buttonStyle;
- (void).cxx_destruct;
- (void)_updateHighlightImageView;
- (void)setHighlighted:(_Bool)arg1;
- (void)setBackgroundImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithButtonStyle:(long long)arg1;

@end

