//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface _PGPlaybackProgressIndicatorMaskView : UIView
{
    NSArray *_maskRanges;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *maskRanges;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

