//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class PGBackdropView, PGChevronView;

@interface PGStashedView : UIView
{
    unsigned int _active:1;
    unsigned int _stashed:1;
    PGBackdropView *_backdropView;
    PGChevronView *_chevronViewLeftColorBurn;
    PGChevronView *_chevronViewLeftPlusD;
    PGChevronView *_chevronViewRightColorBurn;
    PGChevronView *_chevronViewRightPlusD;
}

- (void).cxx_destruct;
- (void)setStashed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setActive:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isStashed) _Bool stashed;
@property(nonatomic, getter=isActive) _Bool active;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

