//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class AVAsset, AVAssetExportSession, AVAudioMix, AVVideoComposition, NSArray, NSError, NSObject, NSString, NSURL, PFAssetAdjustments;
@protocol OS_dispatch_queue;

@interface PFVideoSharingOperation : NSOperation
{
    AVAsset *_videoAsset;
    AVAudioMix *_audioMix;
    AVVideoComposition *_videoComposition;
    NSArray *_videoMetadata;
    NSObject<OS_dispatch_queue> *_externalIsolation;
    AVAssetExportSession *_exportSession;
    _Bool _beganExport;
    _Bool _operationSuccess;
    NSError *_operationError;
    _Bool _shouldStripMetadata;
    _Bool _shouldStripLocation;
    NSURL *_outputDirectoryURL;
    NSString *_generatedFileName;
    NSURL *_videoURL;
    PFAssetAdjustments *__adjustments;
}

@property(retain, nonatomic, setter=_setAdjustments:) PFAssetAdjustments *_adjustments; // @synthesize _adjustments=__adjustments;
- (void)_setVideoURL:(id)arg1;
@property(copy, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(nonatomic) _Bool shouldStripLocation; // @synthesize shouldStripLocation=_shouldStripLocation;
@property(nonatomic) _Bool shouldStripMetadata; // @synthesize shouldStripMetadata=_shouldStripMetadata;
@property(copy, nonatomic) NSString *generatedFileName; // @synthesize generatedFileName=_generatedFileName;
@property(copy, nonatomic) NSURL *outputDirectoryURL; // @synthesize outputDirectoryURL=_outputDirectoryURL;
- (void).cxx_destruct;
@property(retain, nonatomic) NSError *operationError;
- (void)_setOperationError:(id)arg1;
@property(nonatomic) _Bool success;
- (void)_setSuccess:(_Bool)arg1;
- (void)cancel;
@property(readonly, nonatomic) float progress;
- (_Bool)_runExport;
- (void)_validateMetadata;
- (_Bool)_ensureVideoProperties;
- (void)main;
- (id)initWithVideoURL:(id)arg1 adjustmentData:(id)arg2;

@end

