//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpotlightUI/NSObject-Protocol.h>

@class NSString, NSURL;

@protocol SearchUICardPunchout <NSObject>

@optional
@property(readonly, nonatomic) NSURL *installURL;
@property(readonly, nonatomic) NSURL *punchoutURL;
@property(readonly, nonatomic) NSString *punchoutLabel;
@end

