//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Search/SPAuxiliaryInfo.h>

#import <SpotlightUI/SearchUIAuxiliaryInfo-Protocol.h>

@class NSString;

@interface SPAuxiliaryInfo (SearchUIExtensions) <SearchUIAuxiliaryInfo>
@property(readonly, copy, nonatomic) NSString *bottomTextColor;
@property(readonly, copy, nonatomic) NSString *bottomText;
@property(readonly, copy, nonatomic) NSString *middleText;
@property(readonly, copy, nonatomic) NSString *topText;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

