//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpotlightUI/SFSpeechRecognizerDelegate-Protocol.h>
#import <SpotlightUI/SPSearchAgentDelegate-Protocol.h>
#import <SpotlightUI/SPUISearchDictationViewProtocol-Protocol.h>
#import <SpotlightUI/SPUISearchFirstTimeViewControllerDelegate-Protocol.h>
#import <SpotlightUI/SPUISearchHeaderDelegate-Protocol.h>
#import <SpotlightUI/SPUISearchPluginClientInterface-Protocol.h>
#import <SpotlightUI/SPUISearchResultsActionManagerDelegate-Protocol.h>
#import <SpotlightUI/SPUISearchTableViewDelegate-Protocol.h>
#import <SpotlightUI/SPUISearchViewControllerPresentation-Protocol.h>
#import <SpotlightUI/SearchUIDelegate-Protocol.h>
#import <SpotlightUI/UIGestureRecognizerDelegate-Protocol.h>
#import <SpotlightUI/UINavigationControllerDelegate-Protocol.h>
#import <SpotlightUI/UISearchBarDelegate-Protocol.h>
#import <SpotlightUI/UITableViewDataSource-Protocol.h>
#import <SpotlightUI/UITableViewDelegate-Protocol.h>
#import <SpotlightUI/UITextFieldDelegate-Protocol.h>
#import <SpotlightUI/_SFSpeechRecognitionTaskDelegatePrivate-Protocol.h>

@class NSDate, NSLayoutConstraint, NSMutableSet, NSString, NSTimer, SFSpeechRecognitionTask, SFSpeechRecognizer, SPFeedbackVoiceSearch, SPUISearchDictationView, SPUISearchFirstTimeViewController, SPUISearchHeader, SPUISearchResultsActionManager, SPUISearchTableView, UIPanGestureRecognizer, UISwipeGestureRecognizer, UITapGestureRecognizer, UIView, _UIBackdropView;

@interface SPUISearchViewController : UIViewController <SPUISearchResultsActionManagerDelegate, SPUISearchFirstTimeViewControllerDelegate, UITableViewDelegate, UITableViewDataSource, SPUISearchTableViewDelegate, SPSearchAgentDelegate, UISearchBarDelegate, UINavigationControllerDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate, SPUISearchHeaderDelegate, _SFSpeechRecognitionTaskDelegatePrivate, SFSpeechRecognizerDelegate, SearchUIDelegate, SPUISearchViewControllerPresentation, SPUISearchPluginClientInterface, SPUISearchDictationViewProtocol>
{
    SPUISearchFirstTimeViewController *_firstTimeViewController;
    SPUISearchTableView *_tableView;
    SPUISearchHeader *_searchHeader;
    SPUISearchResultsActionManager *_actionManager;
    UITapGestureRecognizer *_tapRecognizer;
    UISwipeGestureRecognizer *_swipeRecognizer;
    UIPanGestureRecognizer *_panRecognizer;
    double _lastContentOffsetY;
    _Bool _scrollDown;
    _Bool _wasPreviouslyScrolledToTop;
    long long _searchMode;
    long long _visibility;
    long long _firstTimeViewShowCount;
    NSString *_fteString;
    NSString *_fteLearnMoreLink;
    NSString *_fteContinueLink;
    _Bool _duetExpertChanged;
    _Bool _perfMetricsTestInProgress;
    double _triggerTimestamp;
    struct CGPoint _preReachabilityTableViewOrigin;
    struct CGPoint _reachabilityTableViewOrigin;
    _Bool _showingForReachability;
    _Bool _defaultSearchEnabled;
    NSTimer *_completionTimer;
    NSString *_recognizerLocaleName;
    SFSpeechRecognizer *_recognizer;
    SFSpeechRecognitionTask *_currentTask;
    _Bool _activated;
    _Bool _isPresenting;
    _Bool _updateTableWhenFinishedPresenting;
    _Bool _dismissWhenFinishedPresenting;
    _Bool _countedSeenFTE;
    _Bool _fteShown;
    _Bool _feedbackProvided;
    SPUISearchDictationView *_flamesView;
    NSString *_voiceQueryIdentifier;
    SPFeedbackVoiceSearch *_voiceSearchFeedback;
    _Bool _disabledUpdates;
    _Bool _userIsTyping;
    _Bool _avoidRenderFeedback;
    _Bool _isTransitioningZKWBackdropView;
    _Bool _userInitiatedScrollInProgress;
    int _updateSequenceNumber;
    int _lastRenderUpdateSequenceNumber;
    unsigned long long _presentsFromEdge;
    NSDate *_deactivateTime;
    NSTimer *_hysteresisTimer;
    unsigned long long _minimumQueryLengthForTableUpdate;
    double _typingHysteresis;
    NSString *_lastQuery;
    unsigned long long _queryStartTime;
    NSMutableSet *_purgeableTableViewCells;
    _UIBackdropView *_zkwBackdropView;
    double _zkwBackdropViewTransitionProgress;
    NSDate *_timeOfLastZKWUpdate;
    double _zkwExpirationInterval;
    NSTimer *_clearSearchTimer;
    double _clearSearchTimeInterval;
    UIView *_topDividerView;
    unsigned long long _currentPresentationSource;
    NSString *_lastSearchQuery;
    UIView *_replicatorView;
    NSLayoutConstraint *_replicatorViewHeightConstraint;
}

+ (void)openApplicationWithBundleID:(id)arg1 continuationAction:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)openApplicationWithBundleID:(id)arg1;
+ (id)sharedInstance;
@property(retain) NSLayoutConstraint *replicatorViewHeightConstraint; // @synthesize replicatorViewHeightConstraint=_replicatorViewHeightConstraint;
@property(retain) UIView *replicatorView; // @synthesize replicatorView=_replicatorView;
@property int lastRenderUpdateSequenceNumber; // @synthesize lastRenderUpdateSequenceNumber=_lastRenderUpdateSequenceNumber;
@property int updateSequenceNumber; // @synthesize updateSequenceNumber=_updateSequenceNumber;
@property(retain, nonatomic) NSString *lastSearchQuery; // @synthesize lastSearchQuery=_lastSearchQuery;
@property(nonatomic) unsigned long long currentPresentationSource; // @synthesize currentPresentationSource=_currentPresentationSource;
@property(retain) UIView *topDividerView; // @synthesize topDividerView=_topDividerView;
@property double clearSearchTimeInterval; // @synthesize clearSearchTimeInterval=_clearSearchTimeInterval;
@property(retain) NSTimer *clearSearchTimer; // @synthesize clearSearchTimer=_clearSearchTimer;
@property double zkwExpirationInterval; // @synthesize zkwExpirationInterval=_zkwExpirationInterval;
@property(retain) NSDate *timeOfLastZKWUpdate; // @synthesize timeOfLastZKWUpdate=_timeOfLastZKWUpdate;
@property _Bool userInitiatedScrollInProgress; // @synthesize userInitiatedScrollInProgress=_userInitiatedScrollInProgress;
@property double zkwBackdropViewTransitionProgress; // @synthesize zkwBackdropViewTransitionProgress=_zkwBackdropViewTransitionProgress;
@property _Bool isTransitioningZKWBackdropView; // @synthesize isTransitioningZKWBackdropView=_isTransitioningZKWBackdropView;
@property(retain) _UIBackdropView *zkwBackdropView; // @synthesize zkwBackdropView=_zkwBackdropView;
@property(retain) NSMutableSet *purgeableTableViewCells; // @synthesize purgeableTableViewCells=_purgeableTableViewCells;
@property unsigned long long queryStartTime; // @synthesize queryStartTime=_queryStartTime;
@property(retain) NSString *lastQuery; // @synthesize lastQuery=_lastQuery;
@property double typingHysteresis; // @synthesize typingHysteresis=_typingHysteresis;
@property unsigned long long minimumQueryLengthForTableUpdate; // @synthesize minimumQueryLengthForTableUpdate=_minimumQueryLengthForTableUpdate;
@property _Bool avoidRenderFeedback; // @synthesize avoidRenderFeedback=_avoidRenderFeedback;
@property _Bool userIsTyping; // @synthesize userIsTyping=_userIsTyping;
@property(retain) NSTimer *hysteresisTimer; // @synthesize hysteresisTimer=_hysteresisTimer;
@property(retain) NSDate *deactivateTime; // @synthesize deactivateTime=_deactivateTime;
@property(nonatomic) _Bool disabledUpdates; // @synthesize disabledUpdates=_disabledUpdates;
@property(nonatomic) unsigned long long presentsFromEdge; // @synthesize presentsFromEdge=_presentsFromEdge;
- (void).cxx_destruct;
- (void)didSelectActionItemForResult:(id)arg1;
- (id)searchTableView;
- (id)searchHeader;
- (void)_registerForPerfMetricsTestNotifications;
- (_Bool)_shouldUpdateZKWContent:(_Bool)arg1;
- (void)_proactivelyUpdateZKWContent;
- (void)_duetExpertChanged:(id)arg1;
- (void)_springBoardDidGoToHomeScreen:(id)arg1;
- (void)speechRecognitionTask:(id)arg1 didRecordAudioPCMBuffer:(id)arg2;
- (void)speechRecognitionTask:(id)arg1 didFinishSuccessfully:(_Bool)arg2;
- (void)speechRecognitionTaskWasCancelled:(id)arg1;
- (void)speechRecognitionTaskFinishedReadingAudio:(id)arg1;
- (void)speechRecognitionTask:(id)arg1 didFinishRecognition:(id)arg2;
- (void)speechRecognitionTask:(id)arg1 didHypothesizeTranscription:(id)arg2;
- (void)speechRecognitionDidDetectSpeech:(id)arg1;
- (void)handleDictationCompletion:(id)arg1;
- (void)finishDictation;
- (void)stopDictation:(id)arg1;
- (void)startDictation:(id)arg1;
- (void)_showDictationView;
- (void)speechRecognitionTask:(id)arg1 didReceiveSearchResponse:(id)arg2 data:(id)arg3 recognizedText:(id)arg4 stable:(_Bool)arg5 searchType:(long long)arg6;
- (void)speechRecognitionTask:(id)arg1 didReceiveSearchResults:(id)arg2 recognizedText:(id)arg3 stable:(_Bool)arg4 final:(_Bool)arg5;
- (float)audioLevelForFlamesView;
- (void)donePressed;
- (void)animateForReachabilityDeactivatedWithHandler:(CDUnknownBlockType)arg1;
- (void)animateForReachabilityActivatedWithOffsetFactor:(double)arg1 handler:(CDUnknownBlockType)arg2;
- (void)handleCancelReachabilityGesture:(id)arg1;
- (void)configureReachabilityGesture;
- (void)didReceiveMemoryWarning;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)actionManager:(id)arg1 sendFeedback:(id)arg2;
- (void)actionManager:(id)arg1 dismissViewController:(id)arg2 completion:(CDUnknownBlockType)arg3 animated:(_Bool)arg4;
- (void)actionManager:(id)arg1 presentViewController:(id)arg2 completion:(CDUnknownBlockType)arg3 modally:(_Bool)arg4;
- (void)actionManager:(id)arg1 dismissAnimated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)firstTimeViewControllerDidSelectContinueAction:(id)arg1;
- (void)firstTimeViewControllerDidSelectLearnMoreAction:(id)arg1;
- (void)timeToStartDictation:(id)arg1;
- (void)dictationButtonPressed;
- (void)speechRecognizer:(id)arg1 availabilityDidChange:(_Bool)arg2;
- (_Bool)isDictationAvailable;
- (id)recognizer;
- (void)switchFromSearchResultsToZKW;
- (void)cancelButtonPressed;
- (void)_cleanUpAfterScrolling:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)prefetchImagesForScrollDirection:(_Bool)arg1 delta:(double)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didFinishZKWBlur;
- (void)updateZKWBlurProgress:(double)arg1;
- (void)willBeginZKWBlur;
- (void)_addGaussianBlurWithRadius:(double)arg1;
- (void)_animateZKWBlurOut:(_Bool)arg1;
- (void)animateZKWOut;
- (void)animateZKWIn;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)_searchFieldReturnPressed;
- (void)_searchFieldEditingChanged;
- (void)_searchFieldEditingStarted;
- (void)_cacheZKWQueryLive:(_Bool)arg1 allowInternet:(_Bool)arg2;
- (void)_updateQuery;
- (id)inputTypeForInputMode:(id)arg1;
- (void)userFinishedTyping;
- (_Bool)_isPullDownSpotlight;
- (_Bool)_showKeyboardOnPresentation;
- (_Bool)_allowSwipeToDismiss;
- (void)clearPurgeableMemoryForNonVisibleTableViewCells;
- (void)commonDepature;
- (void)_didFinishDismissing;
- (void)willBeginDismissing:(_Bool)arg1;
- (void)_didFinishPresenting;
- (void)didFinishPresenting:(_Bool)arg1;
- (void)updatePresentationProgress:(double)arg1;
- (void)willBeginPresentingAnimated:(_Bool)arg1 fromSource:(unsigned long long)arg2;
- (void)willBeginPresentingAnimated:(_Bool)arg1;
- (long long)maxUnexpandedRowsInSection:(long long)arg1;
- (void)searchTableViewExpansionDidToggleEnd:(id)arg1;
- (void)searchTableViewExpansionDidToggleBegin:(id)arg1;
- (void)tableViewDidFinishReload:(id)arg1;
- (struct CGPoint)tableView:(id)arg1 newContentOffsetAfterUpdate:(struct CGPoint)arg2 context:(id)arg3;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)visibleResultsInSection:(long long)arg1;
- (id)countOfVisibleResultsInSection:(long long)arg1;
- (_Bool)expandableSidewaysRowExistsInSection:(long long)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)viewControllerForPresenting;
- (void)resultSelected:(id)arg1 inSection:(id)arg2;
- (void)resultSelected:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)resultShouldAppearInSidewaysRow:(id)arg1;
- (id)resultsForRowsInSection:(long long)arg1 stopAfterRow:(long long)arg2 expanded:(_Bool)arg3;
- (id)resultsForRow:(long long)arg1 inSection:(long long)arg2 expanded:(_Bool)arg3;
- (id)resultsForRow:(long long)arg1 inSection:(long long)arg2;
- (id)resultsForRowsInSection:(long long)arg1 expanded:(_Bool)arg2;
- (_Bool)sectionCanHaveSidewaysRows:(id)arg1;
- (long long)numberOfPossibleRowsInSection:(long long)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_clearSearchResults;
- (void)searchAgentClearedResults:(id)arg1;
- (void)searchAgentUpdatedResults:(id)arg1;
- (void)updateHeaderHeights;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)_triggerDismissForGesture:(id)arg1;
- (void)_handlePanRecognizer:(id)arg1;
- (void)_handleSwipeRecognizer:(id)arg1;
- (void)_handleTapRecognizer:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (void)_handleDismissGesture;
- (void)_setDismissGestureRecognizersEnabled:(_Bool)arg1;
- (void)clearSearchTimerDidFire;
- (void)stopClearSearchTimer;
- (void)startClearSearchTimer;
- (void)_resetToZKWSearchMode:(long long)arg1 background:(_Bool)arg2;
- (void)foregroundResetToZKWSearchModeNow;
- (void)backgroundResetToFullZKWSearchModeIfNeeded;
- (_Bool)spotlightIsInactiveAndRotating;
- (void)deactivate;
- (void)activate;
- (void)resetCells;
- (void)_sendAbandonmentFeedbackForReason:(unsigned long long)arg1;
- (void)attributionButtonTapped:(id)arg1;
- (void)_sendFeedback:(id)arg1;
- (void)openURL:(id)arg1;
- (id)_actionManager;
- (void)setTableViewShown:(_Bool)arg1;
- (_Bool)tableViewIsShown;
- (void)_reloadTable;
- (void)_updateTableContents;
- (void)sendRenderFeedback;
- (void)sendRenderFeedbackInternal;
- (void)_setFirstTimeViewVisible:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)_isShowingCardDetailView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)_updateFirstTimeExperienceSeenCount;
- (void)_requestFTEStringsIfNeeded;
- (_Bool)_shouldShowFirstTimeView;
- (_Bool)_enoughFirstTimeViewsShown;
@property(readonly, nonatomic) _Bool _hasResults;
- (_Bool)_hasNoQuery;
- (_Bool)_showingKeyboard;
- (void)_setShowingKeyboard:(_Bool)arg1;
- (void)_setVisibility:(long long)arg1;
@property(readonly, nonatomic, getter=isFadingOut) _Bool fadingOut;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
- (void)_dismissAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)dismiss;
- (void)requestGestureResetAnimated:(_Bool)arg1;
- (id)_wrapperProxy;
- (void)setVoiceQueryIdentifier:(id)arg1 reason:(id)arg2;
- (void)viewWillLayoutSubviews;
- (_Bool)shouldShowMoreButtonForSection:(unsigned long long)arg1;
- (void)_updateTableLayoutIfNeeded;
- (void)traitCollectionDidChange:(id)arg1;
- (id)currentSearchModel;
- (void)_updateGestureRecognizerEnabledStatus;
- (void)_updateTableScrollability;
- (void)setSearchMode:(long long)arg1;
- (_Bool)isZKWSearchMode;
- (void)scrollIndexPathToVisible:(id)arg1;
- (void)moveCursorToEnd;
- (void)downArrowPressed:(id)arg1;
- (void)moveCursorToBeginning;
- (void)upArrowPressed:(id)arg1;
- (void)selectHighlightedRow;
- (void)highlightFirstRowIfAble;
- (void)returnPressed;
- (void)leftArrowPressed;
- (void)rightArrowPressed;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)addKeyCommandForKey:(id)arg1 includeCommand:(_Bool)arg2 action:(SEL)arg3;
- (id)headerNextResponder;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

