//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpotlightUI/SPUISearchParsecCell.h>

@class SKUIItemOfferButton, UILabel, UITextView, UIView;

@interface SPUISearchParseciTunesCell : SPUISearchParsecCell
{
    UITextView *_descriptionTextView;
    SKUIItemOfferButton *_appStoreButton;
    UILabel *_ratingLabel;
    UIView *_starView;
}

+ (id)fullStar;
+ (id)halfStar;
+ (id)emptyStar;
+ (_Bool)supportsSection:(id)arg1 result:(id)arg2;
- (void).cxx_destruct;
- (void)updateWithSection:(id)arg1 result:(id)arg2 traitCollection:(id)arg3;
- (id)accessoryViewForSection:(id)arg1 result:(id)arg2;
- (void)updateStarViewWithRating:(double)arg1;
- (void)prepareForReuse;
- (void)updateFontSizes;
- (id)subtitleLabel;
- (id)appStoreButton;
- (void)updateConstraints;
- (void)buttonPressed;
- (void)updateButtonState;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

