//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpotlightUI/NSObject-Protocol.h>

@class SPSearchResult, SPSearchResultSection, UIColor;
@protocol SPUISearchResultDetailsViewControllerDelegate;

@protocol SPUISearchResultDetailsViewController <NSObject>
+ (id)viewControllerForResult:(SPSearchResult *)arg1 inSection:(SPSearchResultSection *)arg2;
@property(readonly) _Bool wantsInset;
@property id <SPUISearchResultDetailsViewControllerDelegate> actionDelegate;
- (void)loadWithCompletionBlock:(void (^)(void))arg1;

@optional
@property(retain) UIColor *contentBackgroundColor;
@end

