//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UITextView;

@interface SPUISearchWikiRowCell : UITableViewCell
{
    UILabel *_labelLabel;
    UITextView *_valueTextView;
}

@property UITextView *valueTextView; // @synthesize valueTextView=_valueTextView;
@property UILabel *labelLabel; // @synthesize labelLabel=_labelLabel;
- (void)layoutSubviews;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (void)awakeFromNib;

@end

