//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@class SPUISearchHeader, UIButton, UIImage;

@interface SPUISearchField : UITextField
{
    SPUISearchHeader *_searchHeader;
    UIButton *_voiceButton;
    UIImage *_clearButtonImage;
    UIImage *_clearButtonImagePressed;
}

@property(retain) UIImage *clearButtonImagePressed; // @synthesize clearButtonImagePressed=_clearButtonImagePressed;
@property(retain) UIImage *clearButtonImage; // @synthesize clearButtonImage=_clearButtonImage;
@property(retain) UIButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property __weak SPUISearchHeader *searchHeader; // @synthesize searchHeader=_searchHeader;
- (void).cxx_destruct;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)arg1;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)arg1;
- (double)rightViewXOffset;
- (double)leftViewXOffset;
- (void)setMicrophoneShown:(_Bool)arg1;
- (void)updateMicrophoneStatus;
- (void)keyboardDictationAvailabiiltyChanged:(id)arg1;
- (void)textInputModeDidChange:(id)arg1;
- (void)searchTextDidChange:(id)arg1;
- (void)microphoneButtonPressed:(id)arg1;
- (id)_clearButtonImageForState:(unsigned long long)arg1;
- (void)layoutSubviews;
- (id)initWithSearchHeader:(id)arg1;

@end

