//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpotlightUI/SPUISearchResultsModalViewControllerAction.h>

#import <SpotlightUI/SKStoreProductViewControllerDelegate-Protocol.h>

@class NSString;

@interface SPUISearchResultsiTunesAction : SPUISearchResultsModalViewControllerAction <SKStoreProductViewControllerDelegate>
{
}

- (void)productViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)requiresNavigationController;
- (void)loadModalViewControllerWithCompletionBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

