//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _MPUOperationNetworkActivityControllerTimer : NSObject
{
    _Bool _canceled;
}

@property(nonatomic, getter=isCanceled) _Bool canceled; // @synthesize canceled=_canceled;
- (id)initWithInterval:(double)arg1 block:(CDUnknownBlockType)arg2;

@end

