//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MPUFoundation/MPUOperation.h>

@class MPUModelResponse, MPUPropertySet, NSProgress;

@interface MPUModelRequest : MPUOperation
{
    _Bool _allowsDeferringExpensiveProperties;
    Class _sectionClass;
    Class _itemClass;
    MPUPropertySet *_sectionProperties;
    MPUPropertySet *_itemProperties;
    MPUModelResponse *_previousResponse;
    NSProgress *_progress;
    CDUnknownBlockType _responseHandler;
}

@property(copy, nonatomic) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(retain, nonatomic) MPUModelResponse *previousResponse; // @synthesize previousResponse=_previousResponse;
@property(nonatomic) _Bool allowsDeferringExpensiveProperties; // @synthesize allowsDeferringExpensiveProperties=_allowsDeferringExpensiveProperties;
@property(copy, nonatomic) MPUPropertySet *itemProperties; // @synthesize itemProperties=_itemProperties;
@property(copy, nonatomic) MPUPropertySet *sectionProperties; // @synthesize sectionProperties=_sectionProperties;
@property(readonly, nonatomic) Class itemClass; // @synthesize itemClass=_itemClass;
@property(readonly, nonatomic) Class sectionClass; // @synthesize sectionClass=_sectionClass;
- (void).cxx_destruct;
- (void)_finishWithResponse:(id)arg1 error:(id)arg2;
- (id)description;
- (id)debugDescription;
- (id)initWithSectionClass:(Class)arg1 itemClass:(Class)arg2;
- (id)init;

@end

