//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPUChangeDetails, MPUPropertySet, MPUSectionedCollection;

@interface MPUModelResponse : NSObject
{
    _Bool _valid;
    MPUPropertySet *_deferredSectionProperties;
    MPUPropertySet *_deferredItemProperties;
    MPUChangeDetails *_changeDetails;
    MPUSectionedCollection *_results;
    MPUPropertySet *_requestedSectionProperties;
    MPUPropertySet *_requestedItemProperties;
}

@property(retain, nonatomic) MPUPropertySet *requestedItemProperties; // @synthesize requestedItemProperties=_requestedItemProperties;
@property(retain, nonatomic) MPUPropertySet *requestedSectionProperties; // @synthesize requestedSectionProperties=_requestedSectionProperties;
@property(copy, nonatomic) MPUSectionedCollection *results; // @synthesize results=_results;
@property(retain, nonatomic) MPUChangeDetails *changeDetails; // @synthesize changeDetails=_changeDetails;
@property(readonly, nonatomic, getter=isValid) _Bool valid; // @synthesize valid=_valid;
@property(retain, nonatomic) MPUPropertySet *deferredItemProperties; // @synthesize deferredItemProperties=_deferredItemProperties;
@property(retain, nonatomic) MPUPropertySet *deferredSectionProperties; // @synthesize deferredSectionProperties=_deferredSectionProperties;
- (void).cxx_destruct;
- (void)_invalidate;
- (id)description;
- (id)debugDescription;
- (id)init;

@end

