//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MPUFoundation/MPUSectionedCollection.h>

@interface MPUMutableSectionedCollection : MPUSectionedCollection
{
}

- (void)appendItem:(id)arg1;
- (void)moveItemFromIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)removeItemAtIndexPath:(id)arg1;
- (void)insertItem:(id)arg1 atIndexPath:(id)arg2;
- (void)appendSection:(id)arg1;
- (void)moveSectionFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)removeSectionAtIndex:(unsigned long long)arg1;
- (void)insertSection:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_initializeAsEmptySectionedCollection;

@end

