//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MPUFoundation/MPUModelObject.h>

@class MPUModelArtist, MPUModelGenre, NSString;

@interface MPUModelMusicVideo : MPUModelObject
{
    _Bool _explicitMusicVideo;
    _Bool _artistUploadedContent;
    NSString *_title;
    MPUModelArtist *_artist;
    MPUModelGenre *_genre;
    double _duration;
    CDUnknownBlockType _artworkCatalogBlock;
}

+ (id)__artworkCatalogBlock__KEY;
+ (id)__artistUploadedContent__KEY;
+ (id)__explicitMusicVideo__KEY;
+ (id)__duration__KEY;
+ (id)__genre__KEY;
+ (id)__artist__KEY;
+ (id)__title__KEY;
@property(copy, nonatomic) CDUnknownBlockType artworkCatalogBlock; // @synthesize artworkCatalogBlock=_artworkCatalogBlock;
@property(nonatomic, getter=isArtistUploadedContent) _Bool artistUploadedContent; // @synthesize artistUploadedContent=_artistUploadedContent;
@property(nonatomic, getter=isExplicitMusicVideo) _Bool explicitMusicVideo; // @synthesize explicitMusicVideo=_explicitMusicVideo;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) MPUModelGenre *genre; // @synthesize genre=_genre;
@property(retain, nonatomic) MPUModelArtist *artist; // @synthesize artist=_artist;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)artworkCatalog;
- (id)descriptionWithType:(unsigned long long)arg1;

@end

