//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MPUFoundation/NSCopying-Protocol.h>
#import <MPUFoundation/NSMutableCopying-Protocol.h>

@class NSArray;

@interface MPUSectionedCollection : NSObject <NSCopying, NSMutableCopying>
{
    NSArray *_sectionedItems;
    NSArray *_sections;
}

- (void).cxx_destruct;
- (void)_initializeAsEmptySectionedCollection;
- (id)lastSection;
- (id)firstSection;
- (void)enumerateItemsInSectionAtIndex:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateSectionsUsingBlock:(CDUnknownBlockType)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (id)sectionAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfSections;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)debugDescription;
- (id)init;

@end

