//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ChatKit/CKImageMediaObject.h>

@interface CKAnimatedImageMediaObject : CKImageMediaObject
{
}

+ (id)UTITypes;
+ (Class)__ck_attachmentItemClass;
- (void)saveAnimatedPreview:(id)arg1 toURL:(id)arg2 forOrientation:(BOOL)arg3;
- (id)generateThumbnailsForWidth:(double)arg1 orientation:(BOOL)arg2;
- (id)savedAnimatedPreviewFromURL:(id)arg1 forOrientation:(BOOL)arg2;
- (id)generateAnimatedPreviewFromThumbnails:(id)arg1 width:(double)arg2 orientation:(BOOL)arg3;
- (id)notificationCenter;
- (id)previewForWidth:(double)arg1 orientation:(BOOL)arg2;
- (id)animatedImageForWidth:(double)arg1;

@end

