//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class UIImageView;

@interface CKPhotoPickerBadgeCell : UICollectionReusableView
{
    _Bool _selected;
    UIImageView *_checkmarkImageView;
}

@property(retain, nonatomic) UIImageView *checkmarkImageView; // @synthesize checkmarkImageView=_checkmarkImageView;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

