//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuickLook/QLPreviewController.h>

#import <ChatKit/QLPreviewControllerDataSource-Protocol.h>

@class NSArray;

@interface CKQLPreviewController : QLPreviewController <QLPreviewControllerDataSource>
{
    NSArray *_previewItems;
}

@property(copy, nonatomic) NSArray *previewItems; // @synthesize previewItems=_previewItems;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (id)previewActions;
- (id)currentPreviewItem;
- (void)setDataSource:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)init;
- (void)dealloc;

@end

