//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ChatKit/CKUIBehaviorNano.h>

@interface CKUIBehaviorNanoNotifications : CKUIBehaviorNano
{
}

- (double)nanoNoteSenderContentSpace;
- (_Bool)showsBalloonBadges;
- (_Bool)modifiesSingleLineBalloonLayout;
- (_Bool)modifiesFirstBalloonLayout;
- (_Bool)showsBalloonChevron;
- (double)previewBalloonMaxWidthForBalloonMaxWidth:(double)arg1;
- (double)balloonMaxWidthForTranscriptWidth:(double)arg1 marginInsets:(struct UIEdgeInsets)arg2 shouldShowPhotoButton:(_Bool)arg3 shouldShowCharacterCount:(_Bool)arg4;
- (_Bool)shouldSizeInitialViewingMessageCount;
- (_Bool)shouldLoadInitialViewingMessageCount;
- (double)bottomTranscriptSpace;
- (double)topTranscriptSpace;
- (_Bool)shouldUseRotisserieScrolling;

@end

