//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSObject;
@protocol OS_dispatch_queue;

@protocol NRMutableStateObserverProtocol
- (void)removeObserver:(id)arg1;
- (id)addObserverQueue:(NSObject<OS_dispatch_queue> *)arg1 withBlock:(void (^)(id <NRDiffProtocol>, id))arg2;
@end

