//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface TNChartRangeList : NSObject
{
    struct __CFUUID *mTableID;
    struct TNChartRangeNode *mNodeList;
    struct TSCERangeCoordinate mUnionRange;
    _Bool mUnionRangeValid;
}

+ (id)rangeListWithRangeRef:(CDStruct_18e81ca1)arg1;
+ (id)rangeListWithTableID:(struct __CFUUID *)arg1 range:(struct TSCERangeCoordinate)arg2;
+ (id)rangeListWithTableID:(struct __CFUUID *)arg1;
@property(readonly, nonatomic) struct __CFUUID *tableID; // @synthesize tableID=mTableID;
- (id)description;
- (void)enumerateRangesUsingBlock:(CDUnknownBlockType)arg1;
- (CDStruct_18e81ca1)unionRangeRef;
- (struct TSCERangeCoordinate)unionRange;
- (struct TSCERangeCoordinate)rangeStartingAfterCell:(CDStruct_0441cfb5)arg1 direction:(int)arg2;
- (struct TSCERangeCoordinate)rangeStartingAtCell:(CDStruct_0441cfb5)arg1 direction:(int)arg2;
- (_Bool)containsRange:(struct TSCERangeCoordinate)arg1;
- (_Bool)containsCell:(CDStruct_0441cfb5)arg1;
- (struct TSCERangeCoordinate)rangeAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfRanges;
- (void)removeAllRanges;
- (void)addRange:(struct TSCERangeCoordinate)arg1 coalesceFlags:(int)arg2;
- (void)dealloc;
- (id)initWithTableID:(struct __CFUUID *)arg1 range:(struct TSCERangeCoordinate)arg2;
- (id)initWithTableID:(struct __CFUUID *)arg1;

@end

