//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSPObject.h>

@protocol TSKAnnotation;

__attribute__((visibility("hidden")))
@interface TSAAnnotationReference : TSPObject
{
    id <TSKAnnotation> _annotation;
    unsigned long long _pageIndex;
}

+ (id)referenceWithObjectContext:(id)arg1 annotation:(id)arg2 searchReference:(id)arg3 pageIndex:(unsigned long long)arg4;
- (void)saveToArchiver:(id)arg1;
- (void)saveToArchive:(struct AnnotationReferenceArchive *)arg1 archiver:(id)arg2;
- (id)initFromUnarchiver:(id)arg1;
- (void)loadFromArchive:(const struct AnnotationReferenceArchive *)arg1 unarchiver:(id)arg2;
- (_Bool)referencesAnnotation:(id)arg1;
- (void)dealloc;
@property(nonatomic) unsigned long long pageIndex;
@property(retain, nonatomic) id <TSKAnnotation> annotation;

@end

