//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, TSCETrackedReference;

@protocol TSCEReferenceTrackerDelegate
- (void)trackedReferenceWasDeleted:(TSCETrackedReference *)arg1 fromOwnerID:(struct __CFUUID *)arg2;
- (NSArray *)cellRangeWasInserted:(CDStruct_18e81ca1)arg1;
- (_Bool)shouldRewriteOnTableIDReassignment;
- (_Bool)shouldRewriteOnTranspose;
- (_Bool)shouldRewriteOnCellMerge;
- (_Bool)shouldRewriteOnTectonicShift;
- (_Bool)shouldRewriteOnRangeMove;
- (_Bool)shouldRewriteOnSort;
- (void)referencedCellWasModified:(TSCETrackedReference *)arg1;

@optional
- (void)updateTrackedHeaders:(struct __CFUUID *)arg1;
@end

