//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <iWorkImport/NSCopying-Protocol.h>
#import <iWorkImport/NSFastEnumeration-Protocol.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface TSCEUidTractList : NSObject <NSCopying, NSFastEnumeration>
{
    unsigned char _stickyBits;
    _Bool _isRangeRef;
    NSMutableArray *_tracts;
}

@property(nonatomic) _Bool isRangeRef; // @synthesize isRangeRef=_isRangeRef;
@property(nonatomic) unsigned char stickyBits; // @synthesize stickyBits=_stickyBits;
- (_Bool)remapUsingColumnUidMap:(const struct TSUUuidMap *)arg1 rowUidMap:(const struct TSUUuidMap *)arg2 clearIfMissing:(_Bool)arg3;
- (_Bool)remapUsingUidMap:(const struct TSUUuidMap *)arg1;
- (id)description;
- (void)pruneUidTractsAtAndAboveIndex:(unsigned char)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)uidTractAtIndex:(unsigned char)arg1;
- (void)appendUidTract:(id)arg1;
- (void)dropPrimaryTract;
- (void)addPrimaryTractForColumnUid:(const UUIDData_5fbc143e *)arg1 rowUid:(const UUIDData_5fbc143e *)arg2;
- (void)addPrimaryTract:(id)arg1;
- (id)primaryTract;
- (unsigned char)tractCount;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)saveToArchive:(struct ASTNodeArrayArchive_ASTUidTractList *)arg1;
- (id)initWithArchive:(const struct ASTNodeArrayArchive_ASTUidTractList *)arg1;

@end

