//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TSCEFormulaMap;

__attribute__((visibility("hidden")))
@interface TSCEFormulaMapEnumerator : NSObject
{
    TSCEFormulaMap *mFormulaMap;
    struct __hash_map_iterator<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<const __CFUUID *, std::__1::vector<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>, std::__1::allocator<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>>>>, void *>*>> {
        struct __hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<const __CFUUID *, std::__1::vector<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>, std::__1::allocator<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>>>>, void *>*> {
            struct __hash_node<std::__1::__hash_value_type<const __CFUUID *, std::__1::vector<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>, std::__1::allocator<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>>>>, void *> *__node_;
        } __i_;
    } mOwnersToFormulasIterator;
    struct __wrap_iter<std::__1::pair<TSUColumnRowCoordinate, TSCEFormula>*> {
        struct pair<TSUColumnRowCoordinate, TSCEFormula> *__i;
    } mFormulasForAnOwnerIterator;
}

- (id).cxx_construct;
- (struct TSCEFormula)nextFormulaGettingOwner:(const struct __CFUUID **)arg1 cellCoordinate:(CDStruct_0441cfb5 *)arg2;
- (_Bool)hasNext;
- (void)dealloc;
- (id)initWithFormulaMap:(id)arg1;

@end

