//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSPFileDataStorage.h>

@class NSString, TSPDirectoryPackage;
@protocol TSPCryptoInfo;

__attribute__((visibility("hidden")))
@interface TSPDirectoryPackageDataStorage : TSPFileDataStorage
{
    unsigned long long _cachedEncodedLength;
    NSString *_path;
    id <TSPCryptoInfo> _decryptionInfo;
    unsigned char _packageIdentifier;
    _Bool _isMissingData;
    TSPDirectoryPackage *_package;
    _Bool _gilligan_isRemote;
}

- (void)setGilligan_isRemote:(_Bool)arg1;
- (_Bool)gilligan_isRemote;
- (void).cxx_destruct;
- (id)AVAssetWithOptions:(id)arg1 forData:(id)arg2;
- (_Bool)copyToTemporaryURL:(id)arg1 encryptionInfo:(id)arg2;
- (_Bool)isInPackage:(id)arg1;
- (id)writeData:(id)arg1 toPackageWriter:(id)arg2 infoMessage:(struct DataInfo *)arg3 preferredFilename:(id)arg4;
- (void)performIOChannelReadWithAccessor:(CDUnknownBlockType)arg1;
- (void)performReadWithAccessor:(CDUnknownBlockType)arg1;
- (void)setIsMissingData:(_Bool)arg1;
- (_Bool)isMissingData;
- (id)decryptionInfo;
- (unsigned long long)encodedLength;
- (unsigned long long)length;
- (unsigned char)packageIdentifier;
- (id)packageLocator;
- (void)didInitializeFromDocumentURL:(id)arg1;
- (id)initWithPath:(id)arg1 package:(id)arg2 decryptionInfo:(id)arg3;

@end

