//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/NSObject-Protocol.h>

@protocol TSTTableInternalGeometryProviding <NSObject>
@property(readonly, nonatomic) unsigned short numberOfHeaderColumns;
@property(readonly, nonatomic) unsigned short numberOfFooterRows;
@property(readonly, nonatomic) unsigned short numberOfHeaderRows;
@property(readonly, nonatomic) unsigned short numberOfColumns;
@property(readonly, nonatomic) unsigned short numberOfRows;
@end

