//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSKDocumentRoot.h>

#import <iWorkImport/TSWPObjectIndex-Protocol.h>

__attribute__((visibility("hidden")))
@interface TSWPDocumentRoot : TSKDocumentRoot <TSWPObjectIndex>
{
}

@property(readonly, nonatomic) _Bool supportHeaderFooterParagraphAlignmentInInspectors;
- (int)verticalAlignmentForTextStorage:(id)arg1;
- (int)naturalAlignmentAtCharIndex:(unsigned long long)arg1 inTextStorage:(id)arg2;
@property(readonly, nonatomic, getter=isChangeTrackingEnabled) _Bool changeTrackingEnabled;
- (id)unavailableDocumentFonts;
- (id)documentFonts;
- (_Bool)useLigatures;
- (struct __CFLocale *)hyphenationLocale;
- (_Bool)shouldHyphenate;
- (id)changeVisibility;
- (id)changeSessionManagerForModel:(id)arg1;
- (void)willClose;
- (void)documentDidLoad;

@end

