//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (AXDictionaryExtensions)
+ (id)dictionaryWithAXAuditIssue:(long long)arg1 description:(id)arg2 resolution:(id)arg3 element:(id)arg4;
@end

